/**
 * Canonical 45 software industries — keep in sync with
 * supabase/migrations/20260917120000_software_45_industries_packages.sql
 */

export const SOFTWARE_INDUSTRIES_45 = [
  'manufacturing',
  'garments',
  'textile-dyeing',
  'feed-mill',
  'poultry-livestock',
  'agriculture',
  'food-beverage-manufacturing',
  'distribution',
  'retail-pos',
  'ecommerce',
  'hospital',
  'pharmacy',
  'diagnostic-laboratory',
  'clinic-dental',
  'restaurant',
  'hotel',
  'real-estate',
  'construction',
  'logistics',
  'courier',
  'automotive',
  'education',
  'training',
  'hr-payroll',
  'accounting',
  'crm',
  'inventory',
  'procurement',
  'field-sales',
  'service-business',
  'professional-services',
  'salon',
  'gym',
  'rental',
  'security-services',
  'facility-management',
  'ngo',
  'microfinance',
  'printing-packaging',
  'furniture-manufacturing',
  'electronics-appliances',
  'jewelry',
  'travel-tourism',
  'agency-management',
  'saas-subscription',
] as const;

export type SoftwareIndustry45Slug = (typeof SOFTWARE_INDUSTRIES_45)[number];

/** Display labels for nav / UI (keep in sync with SQL seed names). */
export const SOFTWARE_INDUSTRY_LABELS: Record<SoftwareIndustry45Slug, string> = {
  manufacturing: 'Manufacturing',
  garments: 'Garments & Apparel',
  'textile-dyeing': 'Textile & Dyeing',
  'feed-mill': 'Feed Mill',
  'poultry-livestock': 'Poultry & Livestock',
  agriculture: 'Agriculture',
  'food-beverage-manufacturing': 'Food & Beverage Manufacturing',
  distribution: 'Wholesale & Distribution',
  'retail-pos': 'Retail & POS',
  ecommerce: 'E-commerce',
  hospital: 'Hospital & Healthcare',
  pharmacy: 'Pharmacy',
  'diagnostic-laboratory': 'Diagnostic & Laboratory',
  'clinic-dental': 'Clinic & Dental',
  restaurant: 'Restaurant & Food Service',
  hotel: 'Hotel & Hospitality',
  'real-estate': 'Real Estate & Property',
  construction: 'Construction',
  logistics: 'Logistics & Transport',
  courier: 'Courier & Delivery',
  automotive: 'Automotive',
  education: 'Education',
  training: 'Training & Coaching',
  'hr-payroll': 'HR & Payroll',
  accounting: 'Accounting & Finance',
  crm: 'CRM & Sales',
  inventory: 'Inventory & Warehouse',
  procurement: 'Procurement',
  'field-sales': 'Field Sales & Sales Force',
  'service-business': 'Service Business',
  'professional-services': 'Professional Services',
  salon: 'Beauty & Salon',
  gym: 'Gym & Fitness',
  rental: 'Rental Business',
  'security-services': 'Security Services',
  'facility-management': 'Facility Management',
  ngo: 'NGO & Nonprofit',
  microfinance: 'Microfinance',
  'printing-packaging': 'Printing & Packaging',
  'furniture-manufacturing': 'Furniture Manufacturing',
  'electronics-appliances': 'Electronics & Appliances',
  jewelry: 'Jewelry',
  'travel-tourism': 'Travel & Tourism',
  'agency-management': 'Agency Management',
  'saas-subscription': 'SaaS & Subscription Business',
};

/** Featured industries shown first on the /software hub (8–12). */
export const SOFTWARE_HUB_PRIORITY_SLUGS: readonly SoftwareIndustry45Slug[] = [
  'manufacturing',
  'garments',
  'feed-mill',
  'distribution',
  'retail-pos',
  'hospital',
  'restaurant',
  'real-estate',
  'construction',
  'logistics',
] as const;

/** Compact home preview set. */
export const SOFTWARE_HOME_PREVIEW_SLUGS: readonly SoftwareIndustry45Slug[] = [
  'manufacturing',
  'garments',
  'feed-mill',
  'retail-pos',
  'hospital',
  'distribution',
] as const;

/** Preferred flagship product slug per industry (from package seed migration). */
export const SOFTWARE_FLAGSHIP_BY_INDUSTRY: Record<string, string> = {
  manufacturing: 'manufacturing-erp',
  garments: 'garments-erp',
  'textile-dyeing': 'textile-erp',
  'feed-mill': 'feed-mill-erp',
  'poultry-livestock': 'poultry-management-erp',
  agriculture: 'fish-farm-management',
  'food-beverage-manufacturing': 'bakery-management',
  distribution: 'distribution-management',
  'retail-pos': 'retail-pos',
  ecommerce: 'ecommerce-admin-dashboard',
  hospital: 'hospital-management',
  pharmacy: 'pharmacy-management',
  'diagnostic-laboratory': 'diagnostic-center-management',
  'clinic-dental': 'clinic-management',
  restaurant: 'restaurant-management',
  hotel: 'hotel-management',
  'real-estate': 'real-estate-erp',
  construction: 'construction-erp',
  logistics: 'logistics-erp',
  courier: 'courier-management',
  automotive: 'dealership-management',
  education: 'school-management',
  training: 'coaching-management',
  'hr-payroll': 'hr-payroll',
  accounting: 'accounting-software',
  crm: 'crm-system',
  inventory: 'inventory-warehouse-erp',
  procurement: 'procurement-software',
  'field-sales': 'sales-force-automation',
  'service-business': 'service-center-management',
  'professional-services': 'professional-services-erp',
  salon: 'salon-management',
  gym: 'gym-management',
  rental: 'rental-management',
  'security-services': 'security-services-software',
  'furniture-manufacturing': 'furniture-manufacturing-erp',
  'electronics-appliances': 'electronics-assembly-erp',
  jewelry: 'jewelry-erp',
  'travel-tourism': 'travel-tourism-software',
  'agency-management': 'manpower-recruiting-erp',
  'saas-subscription': 'saas-management',
  'printing-packaging': 'printing-press-management',
  ngo: 'ngo-management',
  microfinance: 'microfinance-software',
  'facility-management': 'facility-management-software',
};
