import type { LucideIcon } from 'lucide-react';
import {
  Boxes,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Car,
  Cloud,
  Dumbbell,
  Factory,
  Fish,
  GraduationCap,
  Hammer,
  HandCoins,
  HeartPulse,
  Hotel,
  KeyRound,
  Landmark,
  Layers,
  Microscope,
  Package,
  Pill,
  Plane,
  Printer,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Sofa,
  Sprout,
  Stethoscope,
  Store,
  Truck,
  UserCog,
  Users,
  UtensilsCrossed,
  Warehouse,
  Watch,
  Wheat,
  Wrench,
  Zap,
} from 'lucide-react';

/** Icons for Software mega-menu / mobile category links (industry + legacy filter ids). */
export const SOFTWARE_NAV_ICONS: Record<string, LucideIcon> = {
  erp: Building2,
  pos: ShoppingCart,
  crm: Users,
  hrm: UserCog,
  'business-automation': Zap,
  'ecommerce-admin': ShoppingBag,
  manufacturing: Factory,
  garments: Shirt,
  'textile-dyeing': Layers,
  'feed-mill': Wheat,
  'poultry-livestock': Fish,
  agriculture: Sprout,
  'food-beverage-manufacturing': UtensilsCrossed,
  distribution: Package,
  'retail-pos': Store,
  ecommerce: ShoppingBag,
  hospital: HeartPulse,
  pharmacy: Pill,
  'diagnostic-laboratory': Microscope,
  'clinic-dental': Stethoscope,
  restaurant: UtensilsCrossed,
  hotel: Hotel,
  'real-estate': Landmark,
  construction: Hammer,
  logistics: Truck,
  courier: Package,
  automotive: Car,
  education: GraduationCap,
  training: GraduationCap,
  'hr-payroll': UserCog,
  accounting: Calculator,
  inventory: Warehouse,
  procurement: Boxes,
  'field-sales': Briefcase,
  'service-business': Wrench,
  'professional-services': Briefcase,
  salon: Scissors,
  gym: Dumbbell,
  rental: KeyRound,
  'security-services': Shield,
  'facility-management': Building,
  ngo: HandCoins,
  microfinance: HandCoins,
  'printing-packaging': Printer,
  'furniture-manufacturing': Sofa,
  'electronics-appliances': Watch,
  jewelry: Watch,
  'travel-tourism': Plane,
  'agency-management': Users,
  'saas-subscription': Cloud,
  agro: Sprout,
  healthcare: HeartPulse,
  saas: Cloud,
  automation: Layers,
  enterprise: Store,
};

export function softwareNavIcon(id: string): LucideIcon {
  return SOFTWARE_NAV_ICONS[id] ?? Boxes;
}
