import type { SeedSoftwareProduct } from '../types';

const THEME = {
  primary: '#0f2744',
  accent: '#c41e3a',
  sidebar: 'dark' as const,
  density: 'comfortable' as const,
};

/**
 * 15 published products that historically had covers in DB but no local
 * seed gallery. Brings them into SOFTWARE_SEED_PRODUCTS SSOT so generate /
 * ingest / upload can run the same pipeline as core products.
 */
export const GALLERY_MISSING_PRODUCTS: SeedSoftwareProduct[] = [
  {
    slug: 'accounting-software',
    title: 'Accounting & Finance Software',
    brandName: 'LedgerPro',
    logoText: 'LP',
    categorySlug: 'enterprise',
    solutionGroup: 'erp-business-management',
    softwareType: 'Accounting',
    platformType: 'web',
    industry: 'Accounting & finance',
    businessType: 'SME / mid-market finance team',
    primaryUser: 'Accountant / CFO / Finance manager',
    shortDescription: 'Chart of accounts, journals, ledgers, cash/bank and P&L in one finance desk.',
    fullDescription:
      'Business Problem: Spreadsheet books lose audit trail and delay closings. Solution: LedgerPro connects COA, journals, ledgers, cash & bank, AR/AP and management reports for Bangladesh businesses.',
    startingPrice: 45000,
    priceSuffix: '',
    featured: true,
    popular: true,
    sortOrder: 120,
    modules: ['Dashboard', 'Chart of Accounts', 'Journal', 'Ledger', 'Cash & Bank', 'Receivable', 'Payable', 'P&L'],
    dashboardKPIs: ['Cash Balance', 'Bank Balance', 'AR Outstanding', 'AP Outstanding', 'MTD Revenue', 'MTD Expense'],
    terminology: ['Voucher', 'Ledger', 'COA', 'BDT', 'Debit', 'Credit', 'Trial balance', 'P&L'],
    screens: [
      { key: 'dashboard', name: 'Finance Dashboard', category: 'dashboard' },
      { key: 'chart-of-accounts', name: 'Chart of Accounts', category: 'list' },
      { key: 'journal', name: 'Journal', category: 'form' },
      { key: 'ledger', name: 'Ledger', category: 'detail' },
      { key: 'cash-bank', name: 'Cash & Bank', category: 'accounts' },
      { key: 'profit-loss', name: 'Profit & Loss', category: 'reports' },
    ],
    theme: THEME,
    seoTitle: 'Accounting Software Bangladesh | Bridge IT Park',
    seoDescription: 'Accounting software for COA, journals, ledgers, cash/bank and P&L.',
    seoKeywords: ['accounting software bangladesh', 'ledger software', 'finance erp'],
  },
  {
    slug: 'ecommerce-management',
    title: 'E-commerce Management',
    brandName: 'StoreOps',
    logoText: 'SO',
    categorySlug: 'retail-pos',
    solutionGroup: 'business-automation',
    softwareType: 'E-commerce',
    platformType: 'web',
    industry: 'E-commerce',
    businessType: 'Online brand / marketplace seller',
    primaryUser: 'Store manager / Ops lead',
    shortDescription: 'Catalog, orders, customers and sales reports for growing online stores.',
    fullDescription:
      'Run catalog, orders, customers and reporting for Bangladesh e-commerce brands from one operations desk.',
    startingPrice: 35000,
    priceSuffix: '',
    featured: false,
    popular: true,
    sortOrder: 122,
    modules: ['Dashboard', 'Catalog', 'Orders', 'Customers', 'Inventory', 'Reports'],
    dashboardKPIs: ['Orders Today', 'GMV', 'Pending Shipments', 'Returns', 'Active SKUs'],
    terminology: ['SKU', 'COD', 'Courier', 'Variant', 'Campaign'],
    screens: [
      { key: 'dashboard', name: 'Store Dashboard', category: 'dashboard' },
      { key: 'catalog', name: 'Catalog', category: 'list' },
      { key: 'orders', name: 'Orders', category: 'list' },
      { key: 'customers', name: 'Customers', category: 'list' },
      { key: 'inventory', name: 'Inventory', category: 'stock' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: THEME,
    seoTitle: 'E-commerce Management Software | Bridge IT Park',
    seoDescription: 'E-commerce management for catalog, orders, customers and reports.',
    seoKeywords: ['ecommerce management bangladesh', 'online store software'],
  },
  {
    slug: 'ecommerce-admin-operations',
    title: 'E-commerce Operations Suite',
    brandName: 'OpsSuite',
    logoText: 'OS',
    categorySlug: 'retail-pos',
    solutionGroup: 'business-automation',
    softwareType: 'E-commerce Admin',
    platformType: 'web',
    industry: 'E-commerce',
    businessType: 'Multi-channel online brand',
    primaryUser: 'Ops team / Warehouse / Courier desk',
    shortDescription: 'Orders hub, stock sync, courier desk and settlements for multi-channel brands.',
    fullDescription:
      'Day-to-day ops for multi-channel Bangladesh e-commerce — unified orders, channel stock sync, courier handoff and COD settlement.',
    startingPrice: 40000,
    priceSuffix: '',
    featured: true,
    popular: true,
    sortOrder: 6,
    modules: ['Orders Hub', 'Stock Sync', 'Courier Desk', 'Settlements', 'Customers', 'Reports'],
    dashboardKPIs: ['Open Orders', 'Sync Errors', 'Courier Pending', 'COD Due', 'Returns'],
    terminology: ['Channel', 'COD', 'Consignment', 'Settlement', 'Stock sync'],
    // Keys must match existing DB screen rows (hydrate image_url; no duplicates)
    screens: [
      { key: 'orders-hub', name: 'Orders Hub', category: 'list' },
      { key: 'stock-sync', name: 'Stock Sync', category: 'transaction' },
      { key: 'courier-desk', name: 'Courier Desk', category: 'transaction' },
      { key: 'settlements', name: 'Settlements', category: 'accounts' },
      { key: 'customers', name: 'Customers', category: 'list' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: THEME,
    seoTitle: 'E-commerce Operations Suite | Bridge IT Park',
    seoDescription: 'Multi-channel e-commerce ops: orders, stock sync, courier and settlements.',
    seoKeywords: ['ecommerce operations', 'courier desk software', 'cod settlement'],
  },
  {
    slug: 'facility-management-software',
    title: 'Facility Management Software',
    brandName: 'FacilityHQ',
    logoText: 'FH',
    categorySlug: 'service-business',
    solutionGroup: 'business-automation',
    softwareType: 'Facility',
    platformType: 'web',
    industry: 'Facility management',
    businessType: 'Corporate / campus / building ops',
    primaryUser: 'Facility manager / Maintenance lead',
    shortDescription: 'Work orders, assets, vendors and SLA reporting for facility teams.',
    fullDescription:
      'Track tickets, preventive work orders, assets and vendor SLAs for offices, campuses and commercial buildings.',
    startingPrice: 50000,
    priceSuffix: '',
    featured: false,
    popular: false,
    sortOrder: 130,
    modules: ['Dashboard', 'Work Orders', 'Assets', 'Vendors', 'Preventive', 'Reports'],
    dashboardKPIs: ['Open Tickets', 'SLA Breaches', 'Assets Due', 'Vendor Jobs'],
    terminology: ['Work order', 'Asset', 'SLA', 'PPM', 'Vendor'],
    screens: [
      { key: 'dashboard', name: 'Facility Dashboard', category: 'dashboard' },
      { key: 'work-orders', name: 'Work Orders', category: 'list' },
      { key: 'assets', name: 'Assets', category: 'list' },
      { key: 'vendors', name: 'Vendors', category: 'list' },
      { key: 'preventive', name: 'Preventive Maintenance', category: 'transaction' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: THEME,
    seoTitle: 'Facility Management Software | Bridge IT Park',
    seoDescription: 'Facility management for work orders, assets, vendors and SLA reports.',
    seoKeywords: ['facility management software', 'cmms bangladesh'],
  },
  {
    slug: 'furniture-manufacturing-erp',
    title: 'Furniture Manufacturing ERP',
    brandName: 'FurniERP',
    logoText: 'FE',
    categorySlug: 'manufacturing',
    solutionGroup: 'erp-business-management',
    softwareType: 'ERP',
    platformType: 'web',
    industry: 'Furniture manufacturing',
    businessType: 'Furniture factory',
    primaryUser: 'Factory owner / Production planner',
    shortDescription: 'BOM, production orders, materials and costing for furniture factories.',
    fullDescription:
      'Connect BOM, shop-floor production orders, raw materials and cost reports for furniture manufacturers.',
    startingPrice: 70000,
    priceSuffix: '',
    featured: false,
    popular: true,
    sortOrder: 132,
    modules: ['Dashboard', 'BOM', 'Production', 'Inventory', 'Costing', 'Reports'],
    dashboardKPIs: ['Open POs', 'WIP Jobs', 'Material Shortages', 'On-Time %'],
    terminology: ['BOM', 'Shop floor', 'Finish goods', 'Wood lot', 'Upholstery'],
    screens: [
      { key: 'dashboard', name: 'Factory Dashboard', category: 'dashboard' },
      { key: 'bom', name: 'BOM', category: 'detail' },
      { key: 'production', name: 'Production Orders', category: 'transaction' },
      { key: 'inventory', name: 'Inventory', category: 'stock' },
      { key: 'costing', name: 'Costing', category: 'accounts' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: THEME,
    seoTitle: 'Furniture Manufacturing ERP | Bridge IT Park',
    seoDescription: 'Furniture ERP for BOM, production, inventory and costing.',
    seoKeywords: ['furniture erp', 'furniture manufacturing software bangladesh'],
  },
  {
    slug: 'gym-management',
    title: 'Gym Management Software',
    brandName: 'GymDesk',
    logoText: 'GD',
    categorySlug: 'service-business',
    solutionGroup: 'business-automation',
    softwareType: 'Gym',
    platformType: 'web-mobile',
    industry: 'Fitness / gym',
    businessType: 'Gym / fitness center',
    primaryUser: 'Gym owner / Front desk',
    shortDescription: 'Members, memberships, attendance, trainers and payments.',
    fullDescription:
      'Run membership plans, check-ins, trainers and fee collection for gyms and fitness studios.',
    startingPrice: 30000,
    priceSuffix: '',
    featured: false,
    popular: true,
    sortOrder: 134,
    modules: ['Dashboard', 'Members', 'Membership', 'Attendance', 'Trainers', 'Payments'],
    dashboardKPIs: ['Active Members', 'Check-ins Today', 'Due Fees', 'Expiring Plans'],
    terminology: ['Membership', 'Check-in', 'PT', 'Freeze', 'Renewal'],
    screens: [
      { key: 'dashboard', name: 'Gym Dashboard', category: 'dashboard' },
      { key: 'members', name: 'Members', category: 'list' },
      { key: 'membership', name: 'Membership', category: 'form' },
      { key: 'attendance', name: 'Attendance', category: 'transaction' },
      { key: 'trainers', name: 'Trainers', category: 'list' },
      { key: 'payments', name: 'Payments', category: 'accounts' },
    ],
    theme: THEME,
    seoTitle: 'Gym Management Software | Bridge IT Park',
    seoDescription: 'Gym software for members, attendance, trainers and payments.',
    seoKeywords: ['gym management software bangladesh', 'fitness membership software'],
  },
  {
    slug: 'hotel-management',
    title: 'Hotel Management Software',
    brandName: 'StayOS',
    logoText: 'ST',
    categorySlug: 'service-business',
    solutionGroup: 'business-automation',
    softwareType: 'Hotel',
    platformType: 'web',
    industry: 'Hospitality',
    businessType: 'Hotel / guest house',
    primaryUser: 'Front desk / Revenue manager',
    shortDescription: 'Reservations, room status, check-in, housekeeping and billing.',
    fullDescription:
      'Front-office PMS for reservations, room board, guest check-in, housekeeping and folio billing.',
    startingPrice: 55000,
    priceSuffix: '',
    featured: true,
    popular: true,
    sortOrder: 136,
    modules: ['Dashboard', 'Reservations', 'Rooms', 'Check-in', 'Housekeeping', 'Billing'],
    dashboardKPIs: ['Occupancy %', 'Arrivals', 'Departures', 'OOO Rooms', 'ADR'],
    terminology: ['Folio', 'Room type', 'Housekeeping', 'Walk-in', 'ADR'],
    screens: [
      { key: 'dashboard', name: 'Hotel Dashboard', category: 'dashboard' },
      { key: 'reservations', name: 'Reservations', category: 'list' },
      { key: 'rooms', name: 'Room Status', category: 'detail' },
      { key: 'check-in', name: 'Guest Check-in', category: 'transaction' },
      { key: 'housekeeping', name: 'Housekeeping', category: 'list' },
      { key: 'billing', name: 'Billing', category: 'accounts' },
    ],
    theme: THEME,
    seoTitle: 'Hotel Management Software | Bridge IT Park',
    seoDescription: 'Hotel PMS for reservations, rooms, check-in and billing.',
    seoKeywords: ['hotel management software bangladesh', 'pms software'],
  },
  {
    slug: 'jewelry-erp',
    title: 'Jewelry ERP',
    brandName: 'JewelERP',
    logoText: 'JE',
    categorySlug: 'retail-pos',
    solutionGroup: 'erp-business-management',
    softwareType: 'ERP',
    platformType: 'web',
    industry: 'Jewelry retail & manufacturing',
    businessType: 'Jewelry store / workshop',
    primaryUser: 'Owner / Store manager',
    shortDescription: 'Karat inventory, custom orders, tagging and sales for jewelry businesses.',
    fullDescription:
      'Track gold/silver karat stock, custom orders, item tagging and sales reports for jewelry retailers and workshops.',
    startingPrice: 65000,
    priceSuffix: '',
    featured: false,
    popular: true,
    sortOrder: 138,
    modules: ['Dashboard', 'Karat Inventory', 'Orders', 'Tagging', 'Sales', 'Reports'],
    dashboardKPIs: ['Gold Stock (g)', 'Open Orders', 'Today Sales', 'Repair Jobs'],
    terminology: ['Karat', 'Gram', 'Making charge', 'Tag', 'Hallmark'],
    screens: [
      { key: 'dashboard', name: 'Jewelry Dashboard', category: 'dashboard' },
      { key: 'inventory', name: 'Karat Inventory', category: 'stock' },
      { key: 'orders', name: 'Customer Orders', category: 'list' },
      { key: 'tagging', name: 'Tagging', category: 'transaction' },
      { key: 'sales', name: 'Sales', category: 'accounts' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: THEME,
    seoTitle: 'Jewelry ERP Software | Bridge IT Park',
    seoDescription: 'Jewelry ERP for karat stock, orders, tagging and sales.',
    seoKeywords: ['jewelry erp bangladesh', 'gold inventory software'],
  },
  {
    slug: 'microfinance-software',
    title: 'Microfinance Software',
    brandName: 'MicroLedger',
    logoText: 'ML',
    categorySlug: 'enterprise',
    solutionGroup: 'erp-business-management',
    softwareType: 'Microfinance',
    platformType: 'web-mobile',
    industry: 'Microfinance',
    businessType: 'MFI / NGO microcredit',
    primaryUser: 'Branch manager / Loan officer',
    shortDescription: 'Loans, collections, members and PAR reporting for microfinance institutions.',
    fullDescription:
      'Portfolio management for loans, daily collections, members and PAR reports for MFIs in Bangladesh.',
    startingPrice: 80000,
    priceSuffix: '',
    featured: false,
    popular: false,
    sortOrder: 140,
    modules: ['Dashboard', 'Loans', 'Collections', 'Members', 'Groups', 'Reports'],
    dashboardKPIs: ['PAR 30', 'Collection Rate', 'Disbursed MTD', 'Active Loans'],
    terminology: ['PAR', 'Disbursement', 'Collection sheet', 'Group', 'Center'],
    screens: [
      { key: 'dashboard', name: 'Portfolio Dashboard', category: 'dashboard' },
      { key: 'loans', name: 'Loans', category: 'list' },
      { key: 'collections', name: 'Collections', category: 'transaction' },
      { key: 'members', name: 'Members', category: 'list' },
      { key: 'groups', name: 'Groups', category: 'list' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: THEME,
    seoTitle: 'Microfinance Software | Bridge IT Park',
    seoDescription: 'Microfinance software for loans, collections and PAR reports.',
    seoKeywords: ['microfinance software bangladesh', 'mfi loan software'],
  },
  {
    slug: 'ngo-management',
    title: 'NGO Management Software',
    brandName: 'NGODesk',
    logoText: 'NG',
    categorySlug: 'service-business',
    solutionGroup: 'business-automation',
    softwareType: 'NGO',
    platformType: 'web',
    industry: 'NGO / development',
    businessType: 'NGO / foundation',
    primaryUser: 'Program manager / M&E officer',
    shortDescription: 'Projects, beneficiaries, funds and donor reporting for NGOs.',
    fullDescription:
      'Program and fund tracking for beneficiaries, projects, donor funds and compliance reports.',
    startingPrice: 45000,
    priceSuffix: '',
    featured: false,
    popular: false,
    sortOrder: 142,
    modules: ['Dashboard', 'Beneficiaries', 'Projects', 'Funds', 'Donors', 'Reports'],
    dashboardKPIs: ['Active Projects', 'Beneficiaries', 'Fund Utilization %', 'Open Grants'],
    terminology: ['Beneficiary', 'Grant', 'Donor', 'M&E', 'Utilization'],
    screens: [
      { key: 'dashboard', name: 'Program Dashboard', category: 'dashboard' },
      { key: 'beneficiaries', name: 'Beneficiaries', category: 'list' },
      { key: 'projects', name: 'Projects', category: 'list' },
      { key: 'funds', name: 'Funds', category: 'accounts' },
      { key: 'donors', name: 'Donors', category: 'list' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: THEME,
    seoTitle: 'NGO Management Software | Bridge IT Park',
    seoDescription: 'NGO software for projects, beneficiaries, funds and donor reports.',
    seoKeywords: ['ngo management software', 'donor reporting software bangladesh'],
  },
  {
    slug: 'procurement-software',
    title: 'Procurement Software',
    brandName: 'ProcureOS',
    logoText: 'PO',
    categorySlug: 'enterprise',
    solutionGroup: 'erp-business-management',
    softwareType: 'Procurement',
    platformType: 'web',
    industry: 'Procurement',
    businessType: 'Corporate / manufacturing procurement',
    primaryUser: 'Procurement manager / Buyer',
    shortDescription: 'Requisitions, POs, vendors and spend analytics in one desk.',
    fullDescription:
      'Manage PR → RFQ → PO → GRN with vendor scorecards and spend reports for purchasing teams.',
    startingPrice: 50000,
    priceSuffix: '',
    featured: false,
    popular: true,
    sortOrder: 144,
    modules: ['Dashboard', 'Requisitions', 'Purchase Orders', 'Vendors', 'GRN', 'Reports'],
    dashboardKPIs: ['Open PRs', 'Open POs', 'On-Time Delivery %', 'Spend MTD'],
    terminology: ['PR', 'PO', 'RFQ', 'GRN', 'Vendor score'],
    screens: [
      { key: 'dashboard', name: 'Procurement Dashboard', category: 'dashboard' },
      { key: 'requisitions', name: 'Requisitions', category: 'list' },
      { key: 'purchase-orders', name: 'Purchase Orders', category: 'transaction' },
      { key: 'vendors', name: 'Vendors', category: 'list' },
      { key: 'grn', name: 'GRN', category: 'form' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: THEME,
    seoTitle: 'Procurement Software | Bridge IT Park',
    seoDescription: 'Procurement software for PR, PO, vendors and spend reports.',
    seoKeywords: ['procurement software bangladesh', 'purchase order software'],
  },
  {
    slug: 'professional-services-erp',
    title: 'Professional Services ERP',
    brandName: 'ServiceERP',
    logoText: 'SE',
    categorySlug: 'service-business',
    solutionGroup: 'erp-business-management',
    softwareType: 'ERP',
    platformType: 'web',
    industry: 'Professional services',
    businessType: 'Agency / consultancy / IT services',
    primaryUser: 'Delivery manager / Partner',
    shortDescription: 'Projects, timesheets, billing and utilization for service firms.',
    fullDescription:
      'Project delivery, time tracking, client billing and utilization reports for professional services firms.',
    startingPrice: 60000,
    priceSuffix: '',
    featured: false,
    popular: true,
    sortOrder: 146,
    modules: ['Dashboard', 'Projects', 'Timesheets', 'Billing', 'Resources', 'Reports'],
    dashboardKPIs: ['Utilization %', 'Billable Hours', 'WIP', 'AR Outstanding'],
    terminology: ['Utilization', 'Timesheet', 'Retainer', 'SOW', 'WIP'],
    screens: [
      { key: 'dashboard', name: 'Services Dashboard', category: 'dashboard' },
      { key: 'projects', name: 'Projects', category: 'list' },
      { key: 'timesheets', name: 'Timesheets', category: 'form' },
      { key: 'billing', name: 'Billing', category: 'accounts' },
      { key: 'resources', name: 'Resources', category: 'list' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: THEME,
    seoTitle: 'Professional Services ERP | Bridge IT Park',
    seoDescription: 'Services ERP for projects, timesheets, billing and utilization.',
    seoKeywords: ['professional services erp', 'timesheet billing software'],
  },
  {
    slug: 'rental-management',
    title: 'Rental Management Software',
    brandName: 'RentDesk',
    logoText: 'RD',
    categorySlug: 'service-business',
    solutionGroup: 'business-automation',
    softwareType: 'Rental',
    platformType: 'web',
    industry: 'Equipment / asset rental',
    businessType: 'Rental company',
    primaryUser: 'Rental desk / Fleet manager',
    shortDescription: 'Assets, bookings, returns and rental billing.',
    fullDescription:
      'Manage rental fleet, bookings, returns and invoicing for equipment and asset rental businesses.',
    startingPrice: 40000,
    priceSuffix: '',
    featured: false,
    popular: false,
    sortOrder: 148,
    modules: ['Dashboard', 'Assets', 'Bookings', 'Returns', 'Billing', 'Reports'],
    dashboardKPIs: ['Utilization %', 'Out on Rent', 'Due Returns', 'Revenue MTD'],
    terminology: ['Booking', 'Deposit', 'Return', 'Damage charge', 'Fleet'],
    screens: [
      { key: 'dashboard', name: 'Rental Dashboard', category: 'dashboard' },
      { key: 'assets', name: 'Rental Assets', category: 'list' },
      { key: 'bookings', name: 'Bookings', category: 'transaction' },
      { key: 'returns', name: 'Returns', category: 'form' },
      { key: 'billing', name: 'Billing', category: 'accounts' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: THEME,
    seoTitle: 'Rental Management Software | Bridge IT Park',
    seoDescription: 'Rental software for assets, bookings, returns and billing.',
    seoKeywords: ['rental management software', 'equipment rental software bangladesh'],
  },
  {
    slug: 'security-services-software',
    title: 'Security Services Software',
    brandName: 'GuardOS',
    logoText: 'GO',
    categorySlug: 'service-business',
    solutionGroup: 'business-automation',
    softwareType: 'Security',
    platformType: 'web-mobile',
    industry: 'Manpower security',
    businessType: 'Security agency',
    primaryUser: 'Ops manager / Site supervisor',
    shortDescription: 'Sites, roster, guard attendance and client billing.',
    fullDescription:
      'Manpower security ops — client sites, shift roster, guard attendance and monthly billing.',
    startingPrice: 45000,
    priceSuffix: '',
    featured: false,
    popular: false,
    sortOrder: 150,
    modules: ['Dashboard', 'Sites', 'Roster', 'Attendance', 'Guards', 'Billing'],
    dashboardKPIs: ['Active Sites', 'On Duty', 'Absent', 'Open Incidents'],
    terminology: ['Site', 'Shift', 'Roster', 'Guard', 'Post'],
    screens: [
      { key: 'dashboard', name: 'Security Dashboard', category: 'dashboard' },
      { key: 'sites', name: 'Sites', category: 'list' },
      { key: 'roster', name: 'Roster', category: 'detail' },
      { key: 'attendance', name: 'Attendance', category: 'transaction' },
      { key: 'guards', name: 'Guards', category: 'list' },
      { key: 'billing', name: 'Billing', category: 'accounts' },
    ],
    theme: THEME,
    seoTitle: 'Security Services Software | Bridge IT Park',
    seoDescription: 'Security agency software for sites, roster, attendance and billing.',
    seoKeywords: ['security manpower software', 'guard roster software bangladesh'],
  },
  {
    slug: 'travel-tourism-software',
    title: 'Travel & Tourism Software',
    brandName: 'TourDesk',
    logoText: 'TD',
    categorySlug: 'service-business',
    solutionGroup: 'business-automation',
    softwareType: 'Travel',
    platformType: 'web',
    industry: 'Travel & tourism',
    businessType: 'Travel agency',
    primaryUser: 'Travel consultant / Agency owner',
    shortDescription: 'Packages, bookings, payments and supplier management for agencies.',
    fullDescription:
      'Travel desk for tour packages, customer bookings, payments and hotel/airline suppliers.',
    startingPrice: 40000,
    priceSuffix: '',
    featured: false,
    popular: true,
    sortOrder: 152,
    modules: ['Dashboard', 'Packages', 'Bookings', 'Payments', 'Suppliers', 'Visa'],
    dashboardKPIs: ['Bookings Today', 'Pending Payments', 'Departures', 'Open Visas'],
    terminology: ['Package', 'Pax', 'Visa', 'Supplier', 'Itinerary'],
    screens: [
      { key: 'dashboard', name: 'Travel Dashboard', category: 'dashboard' },
      { key: 'packages', name: 'Packages', category: 'list' },
      { key: 'bookings', name: 'Bookings', category: 'transaction' },
      { key: 'payments', name: 'Payments', category: 'accounts' },
      { key: 'suppliers', name: 'Suppliers', category: 'list' },
      { key: 'visa', name: 'Visa Process', category: 'detail' },
    ],
    theme: THEME,
    seoTitle: 'Travel & Tourism Software | Bridge IT Park',
    seoDescription: 'Travel agency software for packages, bookings, payments and suppliers.',
    seoKeywords: ['travel agency software bangladesh', 'tour booking software'],
  },
];

export const GALLERY_MISSING_SLUGS = GALLERY_MISSING_PRODUCTS.map((p) => p.slug);
