import type { SeedSoftwareProduct } from '../types';

/** Eight new maturity-ladder products for Garments + Feed Mill (Standards stay in catalog.ts). */
export const MATURITY_LADDER_PRODUCTS: SeedSoftwareProduct[] = [
  // ─── GARMENTS ───
  {
    slug: 'garments-starter-software',
    title: 'Garments Starter',
    brandName: 'GarmentStart',
    logoText: 'GS',
    categorySlug: 'garments-textile',
    solutionGroup: 'erp-business-management',
    softwareType: 'ERP',
    platformType: 'web',
    industry: 'Apparel manufacturing',
    businessType: 'Small garments workshop / buying house / subcontract factory',
    primaryUser: 'Workshop owner / Merchandiser',
    shortDescription: 'Simple garments order and production management for small workshops.',
    fullDescription:
      'Business Problem: Small workshops and buying houses lose track of buyer styles, basic production and delivery on paper notebooks. Solution: Garments Starter keeps buyers, styles, orders, size/color, production entry, stock and delivery in one light system without heavy ERP screens. Main Modules: Buyer, Style, Order Booking, Size/Color, Production Entry, Stock, Delivery and Basic Reports. Who It Is For: Small garments workshops, buying houses and subcontract factories in Bangladesh.',
    startingPrice: 25000,
    priceSuffix: '',
    featured: false,
    popular: true,
    sortOrder: 10,
    modules: [
      'Buyer Management',
      'Style Management',
      'Order Booking',
      'Basic Size/Color',
      'Production Entry',
      'Stock',
      'Delivery',
      'Basic Reports',
    ],
    dashboardKPIs: ['Open Orders', 'Styles In Hand', 'Today Production', 'Pending Delivery'],
    terminology: ['Buyer', 'Style', 'Order', 'Size Run', 'Color', 'Production Entry', 'Stock', 'Delivery Challan'],
    screens: [
      { key: 'dashboard', name: 'Dashboard', category: 'dashboard' },
      { key: 'buyers', name: 'Buyers', category: 'list' },
      { key: 'styles', name: 'Styles', category: 'list' },
      { key: 'orders', name: 'Orders', category: 'form' },
      { key: 'size-color', name: 'Size/Color', category: 'detail' },
      { key: 'production-entry', name: 'Production Entry', category: 'transaction' },
      { key: 'stock', name: 'Stock', category: 'stock' },
      { key: 'delivery', name: 'Delivery', category: 'transaction' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: { primary: '#2563eb', accent: '#67e8f9', sidebar: 'light', density: 'comfortable' },
    seoTitle: 'Garments Starter Software for Small Factories | Bridge IT Park',
    seoDescription:
      'Affordable garments software for small workshops—manage buyers, styles, orders, production and delivery without complex ERP.',
    seoKeywords: ['garments software for small business', 'garments starter software', 'small garments factory software bangladesh'],
  },
  {
    slug: 'garments-production-management',
    title: 'Garments Production Management',
    brandName: 'GarmentProd',
    logoText: 'GP',
    categorySlug: 'garments-textile',
    solutionGroup: 'erp-business-management',
    softwareType: 'ERP',
    platformType: 'web',
    industry: 'Apparel manufacturing',
    businessType: 'Small/medium garments factory',
    primaryUser: 'Production manager / Cutting in-charge / Floor supervisor',
    shortDescription: 'Production-focused garments management from cutting to finishing.',
    fullDescription:
      'Business Problem: Factories lose line efficiency when cutting, sewing and finishing live in separate notebooks. Solution: Garments Production Management tracks buyer/style orders through planning, cutting, sewing, finishing, employee output, rejection and ready stock. Main Modules: Buyer & Style, Sales Order, Production Planning, Cutting, Sewing, Finishing, Line Output, Rejection, Ready Stock, Delivery and Production Reports. Who It Is For: Small and medium apparel factories that need floor control before full commercial ERP.',
    startingPrice: 50000,
    priceSuffix: '',
    featured: true,
    popular: true,
    sortOrder: 20,
    modules: [
      'Buyer & Style',
      'Sales Order',
      'Production Planning',
      'Cutting',
      'Sewing',
      'Finishing',
      'Line Production',
      'Employee Output',
      'Rejection',
      'Ready Stock',
      'Delivery',
      'Production Reports',
    ],
    dashboardKPIs: [
      'Today Cutting',
      'Today Sewing',
      'Today Finishing',
      'Line Efficiency %',
      'Pending Quantity',
      'Ready Stock',
    ],
    terminology: ['Cut plan', 'Line', 'Bundle', 'Finishing', 'Rejection', 'Efficiency', 'Ready stock', 'Delivery'],
    screens: [
      { key: 'dashboard', name: 'Dashboard', category: 'dashboard' },
      { key: 'buyer-style', name: 'Buyer & Style', category: 'list' },
      { key: 'sales-order', name: 'Sales Order', category: 'form' },
      { key: 'production-plan', name: 'Production Plan', category: 'list' },
      { key: 'cutting', name: 'Cutting', category: 'transaction' },
      { key: 'sewing', name: 'Sewing', category: 'transaction' },
      { key: 'finishing', name: 'Finishing', category: 'transaction' },
      { key: 'employee-output', name: 'Employee Output', category: 'list' },
      { key: 'rejection', name: 'Rejection', category: 'form' },
      { key: 'ready-stock', name: 'Ready Stock', category: 'stock' },
      { key: 'delivery', name: 'Delivery', category: 'transaction' },
      { key: 'production-reports', name: 'Production Reports', category: 'reports' },
    ],
    theme: { primary: '#0f2744', accent: '#22d3ee', sidebar: 'dark', density: 'comfortable' },
    seoTitle: 'Garments Production Management Software | Bridge IT Park',
    seoDescription:
      'Garments production software for cutting, sewing, finishing, line output and ready stock—built for Bangladesh factories.',
    seoKeywords: ['garments production management software', 'cutting sewing finishing software', 'apparel production software bangladesh'],
  },
  {
    slug: 'garments-erp-professional',
    title: 'Garments ERP Professional',
    brandName: 'GarmentPro+',
    logoText: 'G+',
    categorySlug: 'garments-textile',
    solutionGroup: 'erp-business-management',
    softwareType: 'ERP',
    platformType: 'web',
    industry: 'Apparel manufacturing',
    businessType: 'Large garments factory',
    primaryUser: 'Factory director / Production head / Accounts & HR',
    shortDescription: 'Advanced production, warehouse, workforce and financial control for large factories.',
    fullDescription:
      'Business Problem: Large factories need multi-line production, QC, multi-warehouse, attendance, payroll and approvals beyond basic ERP. Solution: Garments ERP Professional adds capacity overview, quality control, stock transfer, workforce, approval workflow, advanced accounts and audit history on top of production and inventory. Who It Is For: Large apparel factories that need stronger control without full multi-factory enterprise.',
    startingPrice: 200000,
    priceSuffix: '',
    featured: true,
    popular: false,
    sortOrder: 40,
    modules: [
      'Multi-Line Production',
      'Capacity Overview',
      'Quality Control',
      'Multi Warehouse',
      'Stock Transfer',
      'Production Cost',
      'Attendance',
      'Payroll',
      'Approval Workflow',
      'User Roles',
      'Advanced Accounts',
      'Audit History',
      'Management Reports',
    ],
    dashboardKPIs: [
      'Factory Output',
      'Line Efficiency %',
      'QC Pass %',
      'Workforce Present',
      'Warehouse Value',
      'Cost Variance %',
      'Receivable',
      'Payable',
    ],
    terminology: [
      'Capacity',
      'Multi-line',
      'QC',
      'Warehouse',
      'Stock transfer',
      'Attendance',
      'Payroll',
      'Approval',
      'Audit',
    ],
    screens: [
      { key: 'executive-dashboard', name: 'Executive Dashboard', category: 'dashboard' },
      { key: 'orders', name: 'Orders', category: 'list' },
      { key: 'planning', name: 'Planning', category: 'list' },
      { key: 'multi-line-production', name: 'Multi-Line Production', category: 'transaction' },
      { key: 'cutting', name: 'Cutting', category: 'transaction' },
      { key: 'sewing', name: 'Sewing', category: 'transaction' },
      { key: 'finishing', name: 'Finishing', category: 'transaction' },
      { key: 'quality-control', name: 'Quality Control', category: 'form' },
      { key: 'warehouse', name: 'Warehouse', category: 'stock' },
      { key: 'stock-transfer', name: 'Stock Transfer', category: 'transaction' },
      { key: 'costing', name: 'Costing', category: 'accounts' },
      { key: 'attendance', name: 'Attendance', category: 'list' },
      { key: 'payroll', name: 'Payroll', category: 'accounts' },
      { key: 'approvals', name: 'Approvals', category: 'form' },
      { key: 'accounts', name: 'Accounts', category: 'accounts' },
      { key: 'reports', name: 'Reports', category: 'reports' },
      { key: 'audit-log', name: 'Audit Log', category: 'list' },
    ],
    theme: { primary: '#1e3a8a', accent: '#34d399', sidebar: 'dark', density: 'compact' },
    seoTitle: 'Advanced Garments ERP Software | Bridge IT Park',
    seoDescription:
      'Professional garments ERP with multi-line production, QC, warehouse, attendance, payroll and advanced accounts.',
    seoKeywords: ['advanced garments erp', 'garments erp professional', 'apparel factory erp bangladesh'],
  },
  {
    slug: 'garments-enterprise-erp',
    title: 'Garments Enterprise ERP',
    brandName: 'GarmentEnterprise',
    logoText: 'GE',
    categorySlug: 'garments-textile',
    solutionGroup: 'erp-business-management',
    softwareType: 'ERP',
    platformType: 'web',
    industry: 'Apparel manufacturing',
    businessType: 'Multi-factory group / export organization',
    primaryUser: 'Group CEO / COO / Commercial & Finance heads',
    shortDescription: 'Complete garments factory automation for multi-factory and enterprise groups.',
    fullDescription:
      'Business Problem: Export groups need multi-factory capacity, commercial, shipment, HR and finance in one controlled system. Solution: Garments Enterprise ERP covers multi-factory performance, merchandising, capacity planning, production, QC, procurement, warehouses, commercial, shipment, HR/payroll, finance, approvals, audit and executive analytics. Who It Is For: Multi-factory apparel groups and enterprise manufacturers in Bangladesh.',
    startingPrice: 500000,
    priceSuffix: '+',
    featured: false,
    popular: false,
    sortOrder: 50,
    modules: [
      'Multi Factory',
      'Multi Branch',
      'Buyer / Merchandising',
      'Capacity Planning',
      'Production Planning',
      'QC',
      'Procurement',
      'Warehouse',
      'Commercial',
      'Shipment',
      'HR',
      'Payroll',
      'Finance',
      'Approval Engine',
      'Role Permissions',
      'Audit',
      'Executive Analytics',
    ],
    dashboardKPIs: [
      'Group Output',
      'Factory OTIF %',
      'Capacity Utilisation',
      'Shipment Ready',
      'Receivable',
      'Gross Margin %',
      'Workforce',
      'Open Approvals',
    ],
    terminology: [
      'Factory',
      'Capacity',
      'Merchandising',
      'Commercial',
      'Shipment',
      'LC',
      'Executive',
      'Audit',
      'Approval',
    ],
    screens: [
      { key: 'executive-dashboard', name: 'Executive Dashboard', category: 'dashboard' },
      { key: 'factory-performance', name: 'Factory Performance', category: 'reports' },
      { key: 'buyer-merchandising', name: 'Buyer Merchandising', category: 'list' },
      { key: 'order-management', name: 'Order Management', category: 'form' },
      { key: 'capacity-planning', name: 'Capacity Planning', category: 'list' },
      { key: 'production-planning', name: 'Production Planning', category: 'list' },
      { key: 'cutting', name: 'Cutting', category: 'transaction' },
      { key: 'sewing', name: 'Sewing', category: 'transaction' },
      { key: 'finishing', name: 'Finishing', category: 'transaction' },
      { key: 'qc', name: 'QC', category: 'form' },
      { key: 'procurement', name: 'Procurement', category: 'list' },
      { key: 'raw-material-warehouse', name: 'Raw Material Warehouse', category: 'stock' },
      { key: 'ready-stock', name: 'Ready Stock', category: 'stock' },
      { key: 'commercial', name: 'Commercial', category: 'accounts' },
      { key: 'shipment', name: 'Shipment', category: 'transaction' },
      { key: 'hr', name: 'HR', category: 'list' },
      { key: 'payroll', name: 'Payroll', category: 'accounts' },
      { key: 'finance', name: 'Finance', category: 'accounts' },
      { key: 'approvals', name: 'Approvals', category: 'form' },
      { key: 'audit', name: 'Audit', category: 'list' },
      { key: 'executive-reports', name: 'Executive Reports', category: 'reports' },
    ],
    theme: { primary: '#0b1220', accent: '#c9a227', sidebar: 'dark', density: 'compact' },
    seoTitle: 'Enterprise Garments ERP Software | Bridge IT Park',
    seoDescription:
      'Enterprise garments ERP for multi-factory groups—capacity, commercial, shipment, HR, finance and executive analytics.',
    seoKeywords: ['enterprise garments erp', 'multi factory garments software', 'apparel group erp bangladesh'],
  },

  // ─── FEED MILL ───
  {
    slug: 'feed-mill-mini',
    title: 'Feed Mill Mini',
    brandName: 'FeedMini',
    logoText: 'FM',
    categorySlug: 'agro-farming',
    solutionGroup: 'manufacturing-production',
    softwareType: 'Manufacturing',
    platformType: 'web',
    industry: 'Animal feed manufacturing',
    businessType: 'Small feed mill',
    primaryUser: 'Mill owner / Operator',
    shortDescription: 'Simple daily feed mill management for small mills.',
    fullDescription:
      'Business Problem: Small mills track purchase, production and sales on paper and lose stock accuracy. Solution: Feed Mill Mini covers raw material purchase and stock, daily production, finished feed, sales, expense and basic reports with a light interface. Who It Is For: Small feed mills starting digital control.',
    startingPrice: 10000,
    priceSuffix: '',
    featured: false,
    popular: true,
    sortOrder: 10,
    modules: [
      'Raw Material Purchase',
      'Raw Material Stock',
      'Daily Production',
      'Finished Feed',
      'Sales',
      'Expense',
      'Basic Reports',
    ],
    dashboardKPIs: ['Raw Material', "Today's Production", "Today's Sales", 'Total Due'],
    terminology: ['Purchase', 'Maize', 'Soy Meal', 'Production', 'Finished Feed', 'Sales', 'Expense'],
    screens: [
      { key: 'dashboard', name: 'Dashboard', category: 'dashboard' },
      { key: 'purchase', name: 'Purchase', category: 'transaction' },
      { key: 'raw-material-stock', name: 'Raw Material Stock', category: 'stock' },
      { key: 'production', name: 'Production', category: 'transaction' },
      { key: 'finished-feed', name: 'Finished Feed', category: 'stock' },
      { key: 'sales', name: 'Sales', category: 'form' },
      { key: 'expense', name: 'Expense', category: 'accounts' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: { primary: '#059669', accent: '#67e8f9', sidebar: 'light', density: 'comfortable' },
    seoTitle: 'Feed Mill Software for Small Mills | Bridge IT Park',
    seoDescription:
      'Affordable feed mill management software—purchase, production, stock, sales and expense for small mills in Bangladesh.',
    seoKeywords: ['affordable feed mill management software', 'feed mill mini software', 'small feed mill software bangladesh'],
  },
  {
    slug: 'feed-mill-basic',
    title: 'Feed Mill Basic',
    brandName: 'FeedBasic',
    logoText: 'FB',
    categorySlug: 'agro-farming',
    solutionGroup: 'manufacturing-production',
    softwareType: 'Manufacturing',
    platformType: 'web',
    industry: 'Animal feed manufacturing',
    businessType: 'Small growing feed mill',
    primaryUser: 'Mill owner / Storekeeper / Sales',
    shortDescription: 'Feed mill management with purchase, production, parties and receivables.',
    fullDescription:
      'Business Problem: Growing mills need suppliers, customers, receivable and payable beyond mini tools. Solution: Feed Mill Basic adds purchase, raw material, production, finished stock, sales, customers, suppliers, receivable/payable, expense and reports. Who It Is For: Small growing feed mills.',
    startingPrice: 25000,
    priceSuffix: '',
    featured: false,
    popular: true,
    sortOrder: 20,
    modules: [
      'Purchase',
      'Raw Material',
      'Production',
      'Finished Stock',
      'Sales',
      'Customers',
      'Suppliers',
      'Receivable',
      'Payable',
      'Expense',
      'Basic Reports',
    ],
    dashboardKPIs: ['Stock Value', 'Today Production', 'Today Sales', 'Party Due'],
    terminology: ['Supplier', 'Customer', 'Receivable', 'Payable', 'Finished Stock', 'Production', 'Purchase'],
    screens: [
      { key: 'dashboard', name: 'Dashboard', category: 'dashboard' },
      { key: 'purchase', name: 'Purchase', category: 'transaction' },
      { key: 'supplier', name: 'Supplier', category: 'list' },
      { key: 'raw-material', name: 'Raw Material', category: 'stock' },
      { key: 'production', name: 'Production', category: 'transaction' },
      { key: 'finished-stock', name: 'Finished Stock', category: 'stock' },
      { key: 'sales', name: 'Sales', category: 'form' },
      { key: 'customers', name: 'Customers', category: 'list' },
      { key: 'receivable-payable', name: 'Receivable & Payable', category: 'accounts' },
      { key: 'expense', name: 'Expense', category: 'accounts' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: { primary: '#0d9488', accent: '#38bdf8', sidebar: 'brand', density: 'comfortable' },
    seoTitle: 'Feed Mill Management Software | Bridge IT Park',
    seoDescription:
      'Feed mill management software for small growing mills—purchase, production, sales, receivable and payable.',
    seoKeywords: ['feed mill management software', 'feed mill basic software bangladesh'],
  },
  {
    slug: 'feed-mill-erp-professional',
    title: 'Feed Mill ERP Professional',
    brandName: 'FeedPro+',
    logoText: 'F+',
    categorySlug: 'agro-farming',
    solutionGroup: 'manufacturing-production',
    softwareType: 'Manufacturing',
    platformType: 'web',
    industry: 'Animal feed manufacturing',
    businessType: 'Large feed mill',
    primaryUser: 'Mill director / Production & accounts heads',
    shortDescription: 'Advanced feed mill ERP with multi-warehouse, costing, approvals and audit.',
    fullDescription:
      'Business Problem: Large mills need multi-warehouse, production costing, approvals and audit beyond standard dealer ERP. Solution: Feed Mill ERP Professional covers advanced purchase, formula, production planning, batch production, material issue, finished feed, multi-warehouse, stock transfer, dealer sales, dispatch, collection, accounts, approvals and audit. Who It Is For: Large commercial feed mills.',
    startingPrice: 100000,
    priceSuffix: '',
    featured: true,
    popular: false,
    sortOrder: 40,
    modules: [
      'Advanced Purchase',
      'Formula',
      'Production Costing',
      'Dealer Management',
      'Multi Warehouse',
      'Stock Transfer',
      'Sales',
      'Dispatch',
      'Collection',
      'Approval Workflow',
      'User Roles',
      'Advanced Accounts',
      'Audit History',
      'Advanced Reports',
    ],
    dashboardKPIs: [
      'Production MT',
      'Cost / Ton',
      'Warehouse Stock',
      'Dealer Outstanding',
      'Pending Approvals',
      'Gross Profit',
    ],
    terminology: [
      'Formula',
      'Batch',
      'Multi warehouse',
      'Stock transfer',
      'Approval',
      'Audit',
      'Cost/Ton',
      'Dealer',
    ],
    screens: [
      { key: 'management-dashboard', name: 'Management Dashboard', category: 'dashboard' },
      { key: 'purchase', name: 'Purchase', category: 'transaction' },
      { key: 'raw-material', name: 'Raw Material', category: 'stock' },
      { key: 'formula', name: 'Formula', category: 'list' },
      { key: 'production-planning', name: 'Production Planning', category: 'list' },
      { key: 'batch-production', name: 'Batch Production', category: 'transaction' },
      { key: 'material-issue', name: 'Material Issue', category: 'stock' },
      { key: 'finished-feed', name: 'Finished Feed', category: 'stock' },
      { key: 'multi-warehouse', name: 'Multi Warehouse', category: 'stock' },
      { key: 'stock-transfer', name: 'Stock Transfer', category: 'transaction' },
      { key: 'dealer', name: 'Dealer', category: 'list' },
      { key: 'sales', name: 'Sales', category: 'form' },
      { key: 'dispatch', name: 'Dispatch', category: 'transaction' },
      { key: 'collection', name: 'Collection', category: 'accounts' },
      { key: 'accounts', name: 'Accounts', category: 'accounts' },
      { key: 'approvals', name: 'Approvals', category: 'form' },
      { key: 'reports', name: 'Reports', category: 'reports' },
      { key: 'audit-log', name: 'Audit Log', category: 'list' },
    ],
    theme: { primary: '#1e3a5f', accent: '#22d3ee', sidebar: 'dark', density: 'compact' },
    seoTitle: 'Advanced Feed Mill ERP Software | Bridge IT Park',
    seoDescription:
      'Professional feed mill ERP with multi-warehouse, production costing, dealer control, approvals and audit.',
    seoKeywords: ['advanced feed mill erp', 'feed mill erp professional bangladesh'],
  },
  {
    slug: 'feed-mill-enterprise-erp',
    title: 'Feed Mill Enterprise ERP',
    brandName: 'FeedEnterprise',
    logoText: 'FE',
    categorySlug: 'agro-farming',
    solutionGroup: 'manufacturing-production',
    softwareType: 'Manufacturing',
    platformType: 'web',
    industry: 'Animal feed manufacturing',
    businessType: 'Multi-warehouse feed producer / large organization',
    primaryUser: 'Group operations / Sales / Finance / HR',
    shortDescription: 'Enterprise feed mill automation with capacity, QC, dealer network and analytics.',
    fullDescription:
      'Business Problem: Enterprise feed producers need capacity planning, QC, territories, sales teams, HR and analytics across warehouses. Solution: Feed Mill Enterprise ERP covers formula/BOM, production planning, batch production, material requirement, QC, production cost, multi-warehouse, dealer network, territories, sales team, orders, dispatch, collection, accounts, HR/payroll, approvals, audit and management analytics. Who It Is For: Large feed organizations and multi-warehouse producers.',
    startingPrice: 250000,
    priceSuffix: '+',
    featured: false,
    popular: false,
    sortOrder: 50,
    modules: [
      'Formula/BOM',
      'Production Planning',
      'Batch Production',
      'Material Requirement',
      'Quality Control',
      'Production Cost',
      'Multi Warehouse',
      'Dealer Network',
      'Territory',
      'Sales Team',
      'Sales Orders',
      'Dispatch',
      'Collection',
      'Accounts',
      'HR',
      'Payroll',
      'Approval',
      'Audit',
      'Management Analytics',
    ],
    dashboardKPIs: [
      'Production Capacity',
      "Today's Production",
      'Raw Material Value',
      'Cost/Ton',
      'Dealer Sales',
      'Receivable',
      'Warehouse Stock',
      'Gross Profit',
    ],
    terminology: [
      'Capacity',
      'BOM',
      'QC',
      'Territory',
      'Sales team',
      'Warehouse',
      'Analytics',
      'Audit',
    ],
    screens: [
      { key: 'executive-dashboard', name: 'Executive Dashboard', category: 'dashboard' },
      { key: 'production-capacity', name: 'Production Capacity', category: 'reports' },
      { key: 'raw-material', name: 'Raw Material', category: 'stock' },
      { key: 'formula-bom', name: 'Formula / BOM', category: 'list' },
      { key: 'production-planning', name: 'Production Planning', category: 'list' },
      { key: 'batch-production', name: 'Batch Production', category: 'transaction' },
      { key: 'material-requirement', name: 'Material Requirement', category: 'list' },
      { key: 'material-issue', name: 'Material Issue', category: 'stock' },
      { key: 'quality-control', name: 'Quality Control', category: 'form' },
      { key: 'production-cost', name: 'Production Cost', category: 'accounts' },
      { key: 'finished-feed', name: 'Finished Feed', category: 'stock' },
      { key: 'warehouses', name: 'Warehouses', category: 'stock' },
      { key: 'stock-transfer', name: 'Stock Transfer', category: 'transaction' },
      { key: 'dealers', name: 'Dealers', category: 'list' },
      { key: 'territories', name: 'Territories', category: 'list' },
      { key: 'sales-team', name: 'Sales Team', category: 'users' },
      { key: 'sales-order', name: 'Sales Order', category: 'form' },
      { key: 'dispatch', name: 'Dispatch', category: 'transaction' },
      { key: 'collection', name: 'Collection', category: 'accounts' },
      { key: 'accounts', name: 'Accounts', category: 'accounts' },
      { key: 'hr-payroll', name: 'HR & Payroll', category: 'accounts' },
      { key: 'approvals', name: 'Approvals', category: 'form' },
      { key: 'audit', name: 'Audit', category: 'list' },
      { key: 'analytics', name: 'Analytics', category: 'reports' },
    ],
    theme: { primary: '#111827', accent: '#10b981', sidebar: 'dark', density: 'compact' },
    seoTitle: 'Enterprise Feed Mill ERP Software | Bridge IT Park',
    seoDescription:
      'Enterprise feed mill ERP—capacity, QC, multi-warehouse, dealer network, HR and management analytics.',
    seoKeywords: ['enterprise feed mill erp', 'feed mill factory software bangladesh'],
  },
];

export const GARMENTS_LADDER_SLUGS = [
  'garments-starter-software',
  'garments-production-management',
  'garments-erp',
  'garments-erp-professional',
  'garments-enterprise-erp',
] as const;

export const FEED_MILL_LADDER_SLUGS = [
  'feed-mill-mini',
  'feed-mill-basic',
  'feed-mill-erp',
  'feed-mill-erp-professional',
  'feed-mill-enterprise-erp',
] as const;
