import type { SeedSoftwareProduct } from '../types';

/** 10 specialized Garments + Feed Mill catalogs (in addition to maturity ladder). */
export const SPECIALIZED_CATALOG_PRODUCTS: SeedSoftwareProduct[] = [
  // ─── GARMENTS SPECIALIZED ───
  {
    slug: 'garments-merchandising-management',
    title: 'Garments Merchandising Management',
    brandName: 'MerchDesk',
    logoText: 'MD',
    categorySlug: 'garments-textile',
    solutionGroup: 'erp-business-management',
    softwareType: 'Merchandising',
    platformType: 'web',
    industry: 'Apparel merchandising',
    businessType: 'Buying house / Merchandising team / Export factory',
    primaryUser: 'Merchandiser / Buyer coordinator / Sample room',
    shortDescription:
      'Buyer inquiry to order confirmation with samples, costing, T&A and shipment follow-up.',
    fullDescription:
      'Business Problem: Buying houses and merchandising teams lose inquiries, sample status and T&A dates across email and spreadsheets. Solution: Garments Merchandising Management tracks buyers, inquiries, styles, samples, cost sheets, quotations, order confirmation, T&A calendar, fabric/trim requirements, approvals and shipment follow-up. Who It Is For: Buying houses, merchandising teams and export-oriented factories in Bangladesh.',
    startingPrice: 60000,
    priceSuffix: '',
    featured: false,
    popular: true,
    sortOrder: 70,
    modules: [
      'Buyer Management',
      'Inquiry',
      'Style',
      'Sample Tracking',
      'Cost Sheet',
      'Quotation',
      'Order Confirmation',
      'T&A Calendar',
      'Fabric/Trim Requirement',
      'Approval Tracking',
      'Shipment Follow-up',
    ],
    dashboardKPIs: [
      'Active Buyers',
      'New Inquiries',
      'Samples Pending',
      'Orders Confirmed',
      'Approvals Pending',
      'Upcoming Shipment',
    ],
    terminology: [
      'Buyer',
      'Inquiry',
      'Style GM-2401',
      'Sample',
      'Cost Sheet',
      'Quotation',
      'T&A',
      'Approval',
      'PI',
      'Shipment',
    ],
    screens: [
      { key: 'dashboard', name: 'Dashboard', category: 'dashboard' },
      { key: 'buyers', name: 'Buyers', category: 'list' },
      { key: 'inquiries', name: 'Inquiries', category: 'list' },
      { key: 'styles', name: 'Styles', category: 'list' },
      { key: 'sample-tracking', name: 'Sample Tracking', category: 'transaction' },
      { key: 'costing', name: 'Costing', category: 'accounts' },
      { key: 'quotations', name: 'Quotations', category: 'form' },
      { key: 'order-confirmation', name: 'Order Confirmation', category: 'form' },
      { key: 'time-action-calendar', name: 'T&A Calendar', category: 'detail' },
      { key: 'approvals', name: 'Approvals', category: 'list' },
      { key: 'shipment-tracking', name: 'Shipment Tracking', category: 'transaction' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: { primary: '#1e3a5f', accent: '#22d3ee', sidebar: 'light', density: 'comfortable' },
    seoTitle: 'Garments Merchandising Software | Bridge IT Park',
    seoDescription:
      'Garments merchandising software for buying houses—inquiries, samples, costing, T&A calendar and shipment follow-up.',
    seoKeywords: [
      'garments merchandising software',
      'buying house software bangladesh',
      'sample tracking garments',
      'T&A calendar software',
    ],
  },
  {
    slug: 'garments-cutting-sewing-management',
    title: 'Garments Cutting & Sewing Management',
    brandName: 'FloorLine',
    logoText: 'FL',
    categorySlug: 'garments-textile',
    solutionGroup: 'erp-business-management',
    softwareType: 'Production',
    platformType: 'web',
    industry: 'Apparel production floor',
    businessType: 'Production factory / Cutting & sewing unit',
    primaryUser: 'Production manager / Line supervisor / Cutting in-charge',
    shortDescription:
      'Floor-level cutting, sewing, WIP, rejection and line efficiency control.',
    fullDescription:
      'Business Problem: Factories miss targets when cutting plans, bundles and hourly sewing live on paper. Solution: Garments Cutting & Sewing Management covers cutting plan, lay planning, bundles, cutting issue, sewing lines, hourly production, operator output, WIP, rejection, line efficiency and target vs actual. Who It Is For: Production-focused garments factories in Bangladesh.',
    startingPrice: 75000,
    priceSuffix: '',
    featured: true,
    popular: true,
    sortOrder: 80,
    modules: [
      'Cutting Plan',
      'Lay Planning',
      'Bundle',
      'Cutting Issue',
      'Sewing Line',
      'Hourly Production',
      'Operator Output',
      'WIP',
      'Rejection',
      'Line Efficiency',
      'Target vs Actual',
    ],
    dashboardKPIs: ['Cutting Today', 'Sewing Today', 'Active Lines', 'Efficiency %', 'WIP Pcs', 'Rejection %'],
    terminology: [
      'Lay plan',
      'Bundle',
      'Line-03',
      'Hourly output',
      'WIP',
      'Rejection',
      'SMV',
      'Efficiency',
      'Operator',
      'Target',
    ],
    screens: [
      { key: 'production-dashboard', name: 'Production Dashboard', category: 'dashboard' },
      { key: 'cutting-plan', name: 'Cutting Plan', category: 'list' },
      { key: 'lay-plan', name: 'Lay Plan', category: 'detail' },
      { key: 'bundles', name: 'Bundles', category: 'list' },
      { key: 'cutting-issue', name: 'Cutting Issue', category: 'transaction' },
      { key: 'sewing-lines', name: 'Sewing Lines', category: 'list' },
      { key: 'hourly-production', name: 'Hourly Production', category: 'reports' },
      { key: 'operator-output', name: 'Operator Output', category: 'list' },
      { key: 'wip', name: 'WIP', category: 'stock' },
      { key: 'rejection', name: 'Rejection', category: 'form' },
      { key: 'efficiency', name: 'Efficiency', category: 'reports' },
      { key: 'production-report', name: 'Production Report', category: 'reports' },
    ],
    theme: { primary: '#0b1220', accent: '#34d399', sidebar: 'dark', density: 'compact' },
    seoTitle: 'Garments Production Management Software | Cutting & Sewing',
    seoDescription:
      'Garments cutting and sewing software—lay plans, bundles, hourly production, WIP, rejection and line efficiency.',
    seoKeywords: [
      'garments production management software',
      'cutting sewing software bangladesh',
      'line efficiency garments',
      'WIP tracking apparel',
    ],
  },
  {
    slug: 'garments-inventory-warehouse',
    title: 'Garments Inventory & Warehouse',
    brandName: 'StoreFlow',
    logoText: 'SF',
    categorySlug: 'garments-textile',
    solutionGroup: 'inventory-warehouse',
    softwareType: 'Inventory',
    platformType: 'web',
    industry: 'Apparel warehouse / store',
    businessType: 'Garments warehouse / Store department',
    primaryUser: 'Storekeeper / Warehouse in-charge / Inventory controller',
    shortDescription:
      'Fabric, trims and accessories stock with GRN, issue, transfer and valuation.',
    fullDescription:
      'Business Problem: Garments stores lose fabric and trim control when GRN, issues and transfers are manual. Solution: Garments Inventory & Warehouse manages fabric stock, trims, accessories, GRN, material issue, return, stock transfer, warehouses, reorder, lot/batch, stock valuation and consumption variance. Who It Is For: Garments warehouse and store departments in Bangladesh factories.',
    startingPrice: 70000,
    priceSuffix: '',
    featured: false,
    popular: true,
    sortOrder: 90,
    modules: [
      'Fabric Stock',
      'Trims Stock',
      'Accessories',
      'GRN',
      'Material Issue',
      'Return',
      'Stock Transfer',
      'Warehouse',
      'Reorder',
      'Lot/Batch',
      'Stock Valuation',
      'Consumption Variance',
    ],
    dashboardKPIs: [
      'Fabric Value',
      'Trim SKUs',
      'Open GRNs',
      'Pending Issues',
      'Reorder Alerts',
      'Variance %',
    ],
    terminology: [
      'Fabric roll',
      'Trim SKU',
      'GRN',
      'Issue slip',
      'Lot',
      'Warehouse',
      'Reorder',
      'Consumption',
      'Shade',
      'Bin location',
    ],
    screens: [
      { key: 'stock-dashboard', name: 'Stock Dashboard', category: 'dashboard' },
      { key: 'fabric-stock', name: 'Fabric Stock', category: 'stock' },
      { key: 'trims-stock', name: 'Trims Stock', category: 'stock' },
      { key: 'accessories', name: 'Accessories', category: 'stock' },
      { key: 'grn', name: 'GRN', category: 'transaction' },
      { key: 'material-issue', name: 'Material Issue', category: 'transaction' },
      { key: 'return', name: 'Return', category: 'form' },
      { key: 'transfer', name: 'Transfer', category: 'transaction' },
      { key: 'warehouse', name: 'Warehouse', category: 'list' },
      { key: 'consumption', name: 'Consumption', category: 'reports' },
      { key: 'stock-valuation', name: 'Stock Valuation', category: 'accounts' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: { primary: '#334155', accent: '#10b981', sidebar: 'brand', density: 'comfortable' },
    seoTitle: 'Garments Inventory Management Software | Bridge IT Park',
    seoDescription:
      'Garments inventory and warehouse software—fabric, trims, GRN, material issue, transfer and stock valuation.',
    seoKeywords: [
      'garments inventory management software',
      'fabric stock software bangladesh',
      'garments warehouse software',
      'trim inventory apparel',
    ],
  },
  {
    slug: 'garments-hr-payroll',
    title: 'Garments HR & Payroll',
    brandName: 'PeoplePay',
    logoText: 'PP',
    categorySlug: 'garments-textile',
    solutionGroup: 'hrm-payroll',
    softwareType: 'HRM',
    platformType: 'web',
    industry: 'Apparel HR & payroll',
    businessType: 'Medium / large garments factory',
    primaryUser: 'HR manager / Payroll officer / Attendance clerk',
    shortDescription:
      'Factory HR with shifts, attendance, OT, leave, advances and salary sheets.',
    fullDescription:
      'Business Problem: Garments factories struggle with shift attendance, OT and monthly payroll across thousands of operators. Solution: Garments HR & Payroll covers employees, departments, designations, shifts, roster, attendance, OT, leave, advance, loan, payroll, salary sheet, payslip and compliance reports. Who It Is For: Medium and large garments factories in Bangladesh.',
    startingPrice: 80000,
    priceSuffix: '',
    featured: false,
    popular: true,
    sortOrder: 100,
    modules: [
      'Employee',
      'Department',
      'Designation',
      'Shift',
      'Roster',
      'Attendance',
      'OT',
      'Leave',
      'Advance',
      'Loan',
      'Payroll',
      'Salary Sheet',
      'Payslip',
      'Compliance Reports',
    ],
    dashboardKPIs: ['Total Employees', 'Present', 'Absent', 'OT Hours', 'Payroll Due', 'On Leave'],
    terminology: [
      'Employee ID',
      'Shift A',
      'Punch',
      'OT hours',
      'Leave',
      'Advance',
      'Loan',
      'Salary sheet',
      'Payslip',
      'Section',
    ],
    screens: [
      { key: 'hr-dashboard', name: 'HR Dashboard', category: 'dashboard' },
      { key: 'employees', name: 'Employees', category: 'list' },
      { key: 'departments', name: 'Departments', category: 'list' },
      { key: 'shifts', name: 'Shifts', category: 'list' },
      { key: 'attendance', name: 'Attendance', category: 'transaction' },
      { key: 'overtime', name: 'Overtime', category: 'transaction' },
      { key: 'leave', name: 'Leave', category: 'form' },
      { key: 'advance-loan', name: 'Advance & Loan', category: 'accounts' },
      { key: 'payroll', name: 'Payroll', category: 'accounts' },
      { key: 'salary-sheet', name: 'Salary Sheet', category: 'reports' },
      { key: 'payslip', name: 'Payslip', category: 'detail' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: { primary: '#1d4ed8', accent: '#14b8a6', sidebar: 'light', density: 'comfortable' },
    seoTitle: 'Garments Payroll Software | HR & Attendance | Bridge IT Park',
    seoDescription:
      'Garments HR and payroll software—attendance, OT, leave, advances, salary sheet and payslips for factories.',
    seoKeywords: [
      'garments payroll software',
      'garments HR software bangladesh',
      'factory attendance payroll',
      'apparel OT management',
    ],
  },
  {
    slug: 'garments-commercial-export-management',
    title: 'Garments Commercial & Export Management',
    brandName: 'ExportDesk',
    logoText: 'ED',
    categorySlug: 'garments-textile',
    solutionGroup: 'erp-business-management',
    softwareType: 'Commercial',
    platformType: 'web',
    industry: 'Apparel commercial / export',
    businessType: 'Export factory / Commercial department',
    primaryUser: 'Commercial manager / Export officer / Bank liaison',
    shortDescription:
      'PI, LC, back-to-back LC, invoices, packing lists, shipment and bank realization.',
    fullDescription:
      'Business Problem: Export commercial teams track PI, LC, documents and bank realization in scattered files. Solution: Garments Commercial & Export Management handles PI, LC, back-to-back LC, import, export, commercial invoice, packing list, shipment, documentation, bank tracking, payment realization and export reports. Who It Is For: Export factories and commercial departments in Bangladesh.',
    startingPrice: 150000,
    priceSuffix: '',
    featured: true,
    popular: false,
    sortOrder: 110,
    modules: [
      'PI',
      'LC',
      'Back-to-Back LC',
      'Import',
      'Export',
      'Commercial Invoice',
      'Packing List',
      'Shipment',
      'Documentation',
      'Bank Tracking',
      'Payment Realization',
      'Export Reports',
    ],
    dashboardKPIs: [
      'Open PIs',
      'Active LCs',
      'Docs Pending',
      'Shipments',
      'Bank Follow-ups',
      'Realization Due',
    ],
    terminology: [
      'PI',
      'LC',
      'BBLC',
      'Commercial invoice',
      'Packing list',
      'BL',
      'Bank',
      'Realization',
      'HS code',
      'Vessel',
    ],
    screens: [
      { key: 'commercial-dashboard', name: 'Commercial Dashboard', category: 'dashboard' },
      { key: 'pi', name: 'PI', category: 'list' },
      { key: 'lc', name: 'LC', category: 'list' },
      { key: 'back-to-back-lc', name: 'Back-to-Back LC', category: 'detail' },
      { key: 'imports', name: 'Imports', category: 'list' },
      { key: 'exports', name: 'Exports', category: 'list' },
      { key: 'commercial-invoice', name: 'Commercial Invoice', category: 'form' },
      { key: 'packing-list', name: 'Packing List', category: 'form' },
      { key: 'shipment', name: 'Shipment', category: 'transaction' },
      { key: 'bank-tracking', name: 'Bank Tracking', category: 'accounts' },
      { key: 'realization', name: 'Realization', category: 'accounts' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: { primary: '#0f2744', accent: '#c9a227', sidebar: 'dark', density: 'compact' },
    seoTitle: 'Garments Commercial Software | Export & LC Management',
    seoDescription:
      'Garments commercial and export software—PI, LC, packing list, shipment documentation and bank realization.',
    seoKeywords: [
      'garments commercial software',
      'export documentation software bangladesh',
      'LC management garments',
      'apparel export software',
    ],
  },

  // ─── FEED MILL SPECIALIZED ───
  {
    slug: 'feed-production-management',
    title: 'Feed Production Management',
    brandName: 'FeedBatch',
    logoText: 'FB',
    categorySlug: 'agro-farming',
    solutionGroup: 'manufacturing-production',
    softwareType: 'Production',
    platformType: 'web',
    industry: 'Animal feed production',
    businessType: 'Production-focused feed mill',
    primaryUser: 'Production supervisor / Mixer operator / Storekeeper',
    shortDescription:
      'Feed production planning, formula, batches, yield, wastage and finished feed.',
    fullDescription:
      'Business Problem: Feed mills lose yield when batch tickets and material issues are disconnected. Solution: Feed Production Management covers production plan, formula, batch, material requirement, material issue, production entry, yield, wastage, finished feed and production reports. Who It Is For: Production-focused feed mills in Bangladesh.',
    startingPrice: 40000,
    priceSuffix: '',
    featured: false,
    popular: true,
    sortOrder: 70,
    modules: [
      'Production Plan',
      'Formula',
      'Batch',
      'Material Requirement',
      'Material Issue',
      'Production',
      'Yield',
      'Wastage',
      'Finished Feed',
      'Production Reports',
    ],
    dashboardKPIs: ['Today Batches', 'Plan vs Actual MT', 'Yield %', 'Wastage %', 'Finished MT', 'Open Issues'],
    terminology: [
      'Maize',
      'Soybean Meal',
      'Batch ticket',
      'Mixer',
      'Yield',
      'Wastage',
      'Broiler Grower',
      'MT',
      'Premix',
      'Formula',
    ],
    screens: [
      { key: 'production-dashboard', name: 'Production Dashboard', category: 'dashboard' },
      { key: 'production-plan', name: 'Batch Planning', category: 'list' },
      { key: 'material-issue', name: 'Material Issue', category: 'stock' },
      { key: 'production-entry', name: 'Daily Production', category: 'transaction' },
      { key: 'reports', name: 'Production Report', category: 'reports' },
      { key: 'formula', name: 'Formula', category: 'list' },
      { key: 'batches', name: 'Batches', category: 'transaction' },
      { key: 'material-requirement', name: 'Material Requirement', category: 'detail' },
      { key: 'yield-wastage', name: 'Yield & Wastage', category: 'reports' },
      { key: 'finished-feed', name: 'Finished Feed', category: 'stock' },
    ],
    theme: { primary: '#0f2744', accent: '#c41e3a', sidebar: 'brand', density: 'comfortable' },
    seoTitle: 'Feed Production Software | Batch & Yield | Bridge IT Park',
    seoDescription:
      'Feed production management software—formulas, batches, material issue, yield, wastage and finished feed stock.',
    seoKeywords: [
      'feed production software',
      'feed batch production bangladesh',
      'feed mill yield software',
      'animal feed production management',
    ],
  },
  {
    slug: 'feed-formula-costing-software',
    title: 'Feed Formula & Costing Software',
    brandName: 'FormuLab',
    logoText: 'FL',
    categorySlug: 'agro-farming',
    solutionGroup: 'manufacturing-production',
    softwareType: 'Formulation',
    platformType: 'web',
    industry: 'Feed formulation & costing',
    businessType: 'Feed formulation / Costing team',
    primaryUser: 'Nutritionist / Costing officer / Mill owner',
    shortDescription:
      'Ingredient nutrients, formula versions, cost per ton, margin and price simulation.',
    fullDescription:
      'Business Problem: Formulation teams cannot compare recipe versions or react when maize and soy prices move. Solution: Feed Formula & Costing Software manages ingredients, nutrient values, formulas, recipe versions, cost/ton, ingredient cost, production cost, formula comparison, margin and price simulation. Who It Is For: Feed formulation and costing teams in Bangladesh.',
    startingPrice: 50000,
    priceSuffix: '',
    featured: true,
    popular: true,
    sortOrder: 80,
    modules: [
      'Ingredients',
      'Nutrient Values',
      'Formula',
      'Recipe Version',
      'Cost/Ton',
      'Ingredient Cost',
      'Production Cost',
      'Formula Comparison',
      'Margin',
      'Price Simulation',
    ],
    dashboardKPIs: [
      'Active Formulas',
      'Avg Cost/Ton',
      'Ingredient Cost Δ',
      'Production Margin',
      'Versions',
      'Simulations',
    ],
    terminology: [
      'Maize',
      'Soybean Meal',
      'Rice Polish',
      'Wheat Bran',
      'Limestone',
      'Premix',
      'CP %',
      'Cost/Ton',
      'Margin',
      'Recipe v3',
    ],
    screens: [
      { key: 'dashboard', name: 'Formula Dashboard', category: 'dashboard' },
      { key: 'formula-builder', name: 'Formula Builder', category: 'form' },
      { key: 'costing', name: 'Cost Analysis', category: 'accounts' },
      { key: 'nutrients', name: 'Nutrition Target', category: 'detail' },
      { key: 'formula-version', name: 'Formula History', category: 'list' },
      { key: 'ingredients', name: 'Ingredients', category: 'list' },
      { key: 'formula-comparison', name: 'Formula Comparison', category: 'reports' },
      { key: 'cost-per-ton', name: 'Cost Per Ton', category: 'accounts' },
      { key: 'price-simulation', name: 'Price Simulation', category: 'form' },
      { key: 'margin-analysis', name: 'Margin Analysis', category: 'reports' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: { primary: '#0f2744', accent: '#c41e3a', sidebar: 'brand', density: 'comfortable' },
    seoTitle: 'Feed Formula Software | Costing & Nutrition | Bridge IT Park',
    seoDescription:
      'Feed formula and costing software—ingredients, nutrients, recipe versions, cost per ton and margin simulation.',
    seoKeywords: [
      'feed formula software',
      'feed costing software bangladesh',
      'animal feed formulation',
      'feed cost per ton',
    ],
  },
  {
    slug: 'feed-dealer-distribution-management',
    title: 'Feed Dealer & Distribution Management',
    brandName: 'DealerNet',
    logoText: 'DN',
    categorySlug: 'agro-farming',
    solutionGroup: 'distribution-dealership',
    softwareType: 'Distribution',
    platformType: 'web',
    industry: 'Feed dealer network',
    businessType: 'Feed company with dealer network',
    primaryUser: 'Sales manager / Area manager / Collection officer',
    shortDescription:
      'Dealer territories, credit limits, dispatch, collection and outstanding control.',
    fullDescription:
      'Business Problem: Feed companies lose control of dealer credit, routes and outstanding when sales and dispatch are separate. Solution: Feed Dealer & Distribution Management covers dealers, territories, routes, sales orders, credit limits, dispatch, collection, dealer ledger, outstanding, sales targets and territory performance. Who It Is For: Feed companies with dealer networks in Bangladesh.',
    startingPrice: 75000,
    priceSuffix: '',
    featured: true,
    popular: true,
    sortOrder: 90,
    modules: [
      'Dealer',
      'Territory',
      'Route',
      'Sales Order',
      'Credit Limit',
      'Dispatch',
      'Collection',
      'Dealer Ledger',
      'Outstanding',
      'Sales Target',
      'Territory Performance',
    ],
    dashboardKPIs: [
      'Active Dealers',
      'Today Orders',
      'Dispatch MT',
      'Collections',
      'Outstanding',
      'Target %',
    ],
    terminology: [
      'Agro Dealer North',
      'Territory',
      'Route',
      'Credit limit',
      'Challan',
      'Collection',
      'Outstanding',
      'Target',
      'Broiler Finisher',
      'MT',
    ],
    screens: [
      { key: 'sales-dashboard', name: 'Dealer Dashboard', category: 'dashboard' },
      { key: 'sales-order', name: 'Sales Order', category: 'form' },
      { key: 'dispatch', name: 'Dispatch', category: 'transaction' },
      { key: 'collection', name: 'Collection', category: 'accounts' },
      { key: 'dealer-ledger', name: 'Dealer Ledger', category: 'accounts' },
      { key: 'dealers', name: 'Dealers', category: 'list' },
      { key: 'territories', name: 'Territories', category: 'list' },
      { key: 'routes', name: 'Routes', category: 'list' },
      { key: 'credit-limit', name: 'Credit Limit', category: 'detail' },
      { key: 'outstanding', name: 'Outstanding', category: 'reports' },
      { key: 'sales-target', name: 'Sales Target', category: 'reports' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: { primary: '#0f2744', accent: '#c41e3a', sidebar: 'brand', density: 'comfortable' },
    seoTitle: 'Feed Dealer Management Software | Distribution | Bridge IT Park',
    seoDescription:
      'Feed dealer and distribution software—territories, credit limits, dispatch, collection and outstanding.',
    seoKeywords: [
      'feed dealer management software',
      'feed distribution software bangladesh',
      'dealer ledger feed mill',
      'feed sales territory software',
    ],
  },
  {
    slug: 'feed-mill-inventory-warehouse',
    title: 'Feed Mill Inventory & Warehouse',
    brandName: 'MillStore',
    logoText: 'MS',
    categorySlug: 'agro-farming',
    solutionGroup: 'inventory-warehouse',
    softwareType: 'Inventory',
    platformType: 'web',
    industry: 'Feed mill warehouse',
    businessType: 'Feed factory with raw & finished warehouses',
    primaryUser: 'Storekeeper / Warehouse manager / QC store',
    shortDescription:
      'Raw material and finished feed warehouses with GRN, lots, reorder and valuation.',
    fullDescription:
      'Business Problem: Feed factories mix raw and finished stock across godowns without lot control. Solution: Feed Mill Inventory & Warehouse manages raw material, finished feed, warehouses, GRN, material issue, stock transfer, lot/batch, reorder, stock adjustment, valuation and expiry/quality status. Who It Is For: Feed factories with separate raw and finished warehouses in Bangladesh.',
    startingPrice: 60000,
    priceSuffix: '',
    featured: false,
    popular: true,
    sortOrder: 100,
    modules: [
      'Raw Material',
      'Finished Feed',
      'Warehouse',
      'GRN',
      'Material Issue',
      'Stock Transfer',
      'Lot/Batch',
      'Reorder',
      'Stock Adjustment',
      'Stock Valuation',
      'Expiry/Quality Status',
    ],
    dashboardKPIs: [
      'Raw Cover Days',
      'Finished MT',
      'Open GRNs',
      'Reorder Alerts',
      'QC Hold Lots',
      'Stock Value',
    ],
    terminology: [
      'Maize lot',
      'Soybean Meal',
      'Godown A',
      'GRN',
      'Transfer',
      'Reorder',
      'QC hold',
      'Expiry',
      'MT',
      'Bin',
    ],
    screens: [
      { key: 'inventory-dashboard', name: 'Inventory Dashboard', category: 'dashboard' },
      { key: 'raw-material', name: 'Raw Stock', category: 'stock' },
      { key: 'warehouses', name: 'Warehouse', category: 'list' },
      { key: 'transfer', name: 'Stock Movement', category: 'transaction' },
      { key: 'reorder', name: 'Reorder', category: 'list' },
      { key: 'finished-feed', name: 'Finished Feed', category: 'stock' },
      { key: 'grn', name: 'Purchase Receipt / GRN', category: 'transaction' },
      { key: 'material-issue', name: 'Material Issue', category: 'transaction' },
      { key: 'lots', name: 'Lots', category: 'list' },
      { key: 'adjustment', name: 'Adjustment', category: 'form' },
      { key: 'valuation', name: 'Valuation', category: 'accounts' },
      { key: 'reports', name: 'Reports', category: 'reports' },
    ],
    theme: { primary: '#0f2744', accent: '#c41e3a', sidebar: 'brand', density: 'comfortable' },
    seoTitle: 'Feed Inventory Software | Warehouse & Lot Control',
    seoDescription:
      'Feed mill inventory and warehouse software—raw materials, finished feed, GRN, lots, reorder and valuation.',
    seoKeywords: [
      'feed inventory software',
      'feed mill warehouse software bangladesh',
      'raw material stock feed',
      'finished feed inventory',
    ],
  },
  {
    slug: 'feed-mill-accounts-finance',
    title: 'Feed Mill Accounts & Finance',
    brandName: 'MillBooks',
    logoText: 'MB',
    categorySlug: 'agro-farming',
    solutionGroup: 'accounting-finance',
    softwareType: 'Finance',
    platformType: 'web',
    industry: 'Feed mill finance',
    businessType: 'Medium / large feed business',
    primaryUser: 'Accountant / Finance manager / Owner',
    shortDescription:
      'Chart of accounts, ledgers, cash/bank, dealer receivables, P&L and cash flow.',
    fullDescription:
      'Business Problem: Feed businesses close books late when dealer receivables and production costs sit outside accounts. Solution: Feed Mill Accounts & Finance provides chart of accounts, journal, ledger, cash, bank, customer/supplier balances, dealer receivable, expenses, P&L, balance sheet and cash flow. Who It Is For: Medium and large feed businesses in Bangladesh.',
    startingPrice: 90000,
    priceSuffix: '',
    featured: false,
    popular: false,
    sortOrder: 110,
    modules: [
      'Chart of Accounts',
      'Journal',
      'Ledger',
      'Cash',
      'Bank',
      'Customer Balance',
      'Supplier Balance',
      'Dealer Receivable',
      'Expense',
      'P&L',
      'Balance Sheet',
      'Cash Flow',
    ],
    dashboardKPIs: [
      'Cash Balance',
      'Bank Balance',
      'Receivables',
      'Payables',
      'Dealer Due',
      'Month P&L',
    ],
    terminology: [
      'COA',
      'Journal',
      'Ledger',
      'Cash book',
      'Bank',
      'Receivable',
      'Payable',
      'Dealer due',
      'P&L',
      'Cash flow',
    ],
    screens: [
      { key: 'finance-dashboard', name: 'Finance Dashboard', category: 'dashboard' },
      { key: 'profit-loss', name: 'Profit & Loss', category: 'reports' },
      { key: 'ledger', name: 'Ledger', category: 'accounts' },
      { key: 'cash', name: 'Cash & Bank', category: 'accounts' },
      { key: 'receivables', name: 'Receivable', category: 'reports' },
      { key: 'bank', name: 'Bank', category: 'accounts' },
      { key: 'chart-of-accounts', name: 'Chart of Accounts', category: 'list' },
      { key: 'journal', name: 'Journal', category: 'form' },
      { key: 'payables', name: 'Payable', category: 'reports' },
      { key: 'dealer-balance', name: 'Dealer Balance / Ageing', category: 'accounts' },
      { key: 'expenses', name: 'Expenses', category: 'transaction' },
      { key: 'financial-reports', name: 'Financial Reports', category: 'reports' },
    ],
    theme: { primary: '#0f2744', accent: '#c41e3a', sidebar: 'brand', density: 'comfortable' },
    seoTitle: 'Feed Mill Accounting Software | Finance & Ledgers',
    seoDescription:
      'Feed mill accounts and finance software—ledgers, cash/bank, dealer receivables, P&L, balance sheet and cash flow.',
    seoKeywords: [
      'feed mill accounting software',
      'feed mill finance software bangladesh',
      'dealer receivable accounts',
      'feed business P&L software',
    ],
  },
];

export const GARMENTS_SPECIALIZED_SLUGS = [
  'garments-accessories-erp',
  'garments-merchandising-management',
  'garments-cutting-sewing-management',
  'garments-inventory-warehouse',
  'garments-hr-payroll',
  'garments-commercial-export-management',
] as const;

export const FEED_MILL_SPECIALIZED_SLUGS = [
  'feed-production-management',
  'feed-formula-costing-software',
  'feed-dealer-distribution-management',
  'feed-mill-inventory-warehouse',
  'feed-mill-accounts-finance',
] as const;
