import type { SeedCreativeMarketingProduct } from '../types';

const designAssets = (prefix: string, names: string[]): SeedCreativeMarketingProduct['assets'] =>
  names.map((name, i) => ({
    key: `${prefix}-${i + 1}`,
    name,
    kind: i === 0 ? 'mockup' : 'portfolio',
  }));

const marketingScreens: SeedCreativeMarketingProduct['assets'] = [
  { key: 'campaign-overview', name: 'Campaign Overview', kind: 'dashboard' },
  { key: 'ad-set-performance', name: 'Ad Set Performance', kind: 'dashboard' },
  { key: 'creative-performance', name: 'Creative Performance', kind: 'dashboard' },
  { key: 'lead-funnel', name: 'Lead Funnel', kind: 'dashboard' },
  { key: 'pixel-events', name: 'Pixel Events', kind: 'dashboard' },
  { key: 'audience-breakdown', name: 'Audience Breakdown', kind: 'dashboard' },
  { key: 'budget-overview', name: 'Budget Overview', kind: 'dashboard' },
  { key: 'conversion-report', name: 'Conversion Report', kind: 'dashboard' },
  { key: 'retargeting-setup', name: 'Retargeting Setup', kind: 'dashboard' },
  { key: 'monthly-report', name: 'Monthly Report', kind: 'dashboard' },
];

export const CREATIVE_MARKETING_SEED_PRODUCTS: SeedCreativeMarketingProduct[] = [
  {
    slug: 'social-media-post-design',
    title: 'Social Media Post Design',
    serviceGroup: 'social-media-design',
    serviceType: 'Design',
    serviceSubcategory: 'graphics-design',
    targetBusiness: 'Retail, restaurants, education, local brands',
    pricingModel: 'package',
    shortDescription: 'Scroll-stopping posts for Facebook and Instagram.',
    outcomeLine: 'Consistent brand creatives ready to publish.',
    fullDescription:
      'Business Problem: Brands post inconsistently with mismatched colors and weak offers. Solution: We design a cohesive social creative set matched to your products and offers. Deliverables include feed posts, story frames and seasonal variants.',
    startingPrice: 3500,
    priceSuffix: '+',
    featured: true,
    popular: true,
    sortOrder: 10,
    deliverables: ['Feed posts', 'Story creatives', 'Offer variants', 'Source files'],
    relatedSlugs: ['facebook-ads-creative', 'brand-identity-design', 'social-media-management'],
    assets: designAssets('post', [
      'Feed Post Sample',
      'Offer Post',
      'Product Highlight',
      'Story Frame',
      'Carousel Slide',
      'Seasonal Promo',
      'Testimonial Post',
      'New Arrival',
    ]),
    theme: { primary: '#2563EB', accent: '#F59E0B' },
    seoTitle: 'Social Media Post Design Bangladesh | Graphic Design Services',
    seoDescription:
      'Professional social media post design for Facebook and Instagram brands in Bangladesh.',
    seoKeywords: [
      'social media post design bangladesh',
      'graphic design services bangladesh',
      'social media creative design',
    ],
  },
  {
    slug: 'facebook-ads-creative',
    title: 'Facebook Ads Creative Design',
    serviceGroup: 'advertising-creative',
    serviceType: 'Ad Creative',
    serviceSubcategory: 'graphics-design',
    targetBusiness: 'E-commerce and lead-gen advertisers',
    pricingModel: 'package',
    shortDescription: 'Eye-catching campaign creatives for products and services.',
    outcomeLine: 'Ad-ready square, story and carousel creatives.',
    fullDescription:
      'Business Problem: Weak creatives burn ad budget before the offer is clear. Solution: We design conversion-focused Meta ad creatives with clear CTA and offer hierarchy.',
    startingPrice: 4500,
    priceSuffix: '+',
    featured: true,
    popular: true,
    sortOrder: 20,
    deliverables: ['Square ads', 'Story ads', 'Carousel frames', 'Offer posters'],
    relatedSlugs: ['meta-ads-management', 'meta-pixel-capi-setup', 'ecommerce-marketing-package'],
    assets: designAssets('ad', [
      'Square Ad',
      'Story Ad',
      'Carousel 1',
      'Carousel 2',
      'Offer Poster',
      'Collection Ad',
      'Retargeting Ad',
      'Launch Teaser',
    ]),
    theme: { primary: '#2563EB', accent: '#F97316' },
    seoTitle: 'Facebook Ads Creative Design Bangladesh',
    seoDescription: 'Meta ad creative design for product and service campaigns in Bangladesh.',
    seoKeywords: ['facebook ads creative', 'social media creative design', 'ad creative design bangladesh'],
  },
  {
    slug: 'brand-identity-design',
    title: 'Brand Identity Design',
    serviceGroup: 'branding-identity',
    serviceType: 'Branding',
    serviceSubcategory: 'graphics-design',
    targetBusiness: 'New brands and rebrands',
    pricingModel: 'one_time',
    shortDescription: 'Logo, colors and identity basics for a clear brand look.',
    outcomeLine: 'A usable brand kit for web, print and social.',
    fullDescription:
      'Business Problem: Businesses grow with inconsistent logos and colors. Solution: A practical brand identity package covering logo, palette, typography and usage guidance.',
    startingPrice: 12000,
    priceSuffix: '+',
    featured: true,
    popular: true,
    sortOrder: 30,
    deliverables: ['Logo suite', 'Color palette', 'Typography', 'Business card', 'Usage guide'],
    relatedSlugs: ['logo-design', 'packaging-design', 'social-media-post-design', 'visiting-card-design'],
    assets: designAssets('brand', [
      'Logo',
      'Business Card',
      'Brand Colors',
      'Mockup',
      'Letterhead',
      'Social Avatar',
    ]),
    theme: { primary: '#0F2744', accent: '#10B981' },
    seoTitle: 'Brand Identity Design Bangladesh | Brand Identity Design',
    seoDescription: 'Brand identity and logo design packages for Bangladesh businesses.',
    seoKeywords: ['brand identity design', 'logo design bangladesh', 'graphic design services'],
  },
  {
    slug: 'logo-design',
    title: 'Logo Design',
    serviceGroup: 'branding-identity',
    serviceType: 'Branding',
    serviceSubcategory: 'graphics-design',
    targetBusiness: 'Startups and SMEs',
    pricingModel: 'one_time',
    shortDescription: 'Clean logo concepts ready for digital and print use.',
    outcomeLine: 'Primary logo plus usage-ready variations.',
    fullDescription:
      'Business Problem: Placeholder logos weaken trust. Solution: Concept-driven logo design with export-ready files.',
    startingPrice: 5000,
    priceSuffix: '+',
    featured: false,
    popular: false,
    sortOrder: 40,
    deliverables: ['Concept options', 'Final logo', 'PNG/SVG exports'],
    relatedSlugs: ['brand-identity-design', 'visiting-card-design', 'packaging-design'],
    assets: designAssets('logo', ['Primary Logo', 'Icon Mark', 'Wordmark', 'Dark Mockup', 'Light Mockup', 'Favicon']),
    theme: { primary: '#111827', accent: '#EAB308' },
    seoTitle: 'Logo Design Services Bangladesh',
    seoDescription: 'Professional logo design for Bangladesh brands and startups.',
    seoKeywords: ['logo design bangladesh', 'graphic design services bangladesh'],
  },
  {
    slug: 'packaging-design',
    title: 'Packaging Design',
    serviceGroup: 'packaging-print',
    serviceType: 'Print',
    serviceSubcategory: 'graphics-design',
    targetBusiness: 'FMCG, food, cosmetics, retail products',
    pricingModel: 'one_time',
    shortDescription: 'Shelf-ready packaging and label design.',
    outcomeLine: 'Print-ready packaging that fits your product story.',
    fullDescription:
      'Business Problem: Generic packaging fails on shelf and online. Solution: Packaging and label design aligned to brand and print constraints.',
    startingPrice: 8000,
    priceSuffix: '+',
    featured: true,
    popular: true,
    sortOrder: 50,
    deliverables: ['Packaging layout', 'Label design', 'Print-ready files', 'Mockups'],
    relatedSlugs: ['brand-identity-design', 'product-label-design', 'brochure-flyer-design'],
    assets: designAssets('pack', [
      'Box Mockup',
      'Label Front',
      'Label Back',
      'Pouch Design',
      'Dieline Preview',
      'Shelf Mockup',
    ]),
    theme: { primary: '#B45309', accent: '#059669' },
    seoTitle: 'Packaging Design Services Bangladesh',
    seoDescription: 'Product packaging and label design services for Bangladesh brands.',
    seoKeywords: ['packaging design services', 'product packaging design bangladesh'],
  },
  {
    slug: 'product-label-design',
    title: 'Product Label Design',
    serviceGroup: 'packaging-print',
    serviceType: 'Print',
    serviceSubcategory: 'graphics-design',
    targetBusiness: 'Food, cosmetics, supplements',
    pricingModel: 'one_time',
    shortDescription: 'Clear, compliant-ready product labels.',
    outcomeLine: 'Readable labels ready for print vendors.',
    fullDescription:
      'Business Problem: Crowded labels confuse buyers. Solution: Hierarchy-first label layouts with space for required details.',
    startingPrice: 4000,
    priceSuffix: '+',
    featured: false,
    popular: false,
    sortOrder: 55,
    deliverables: ['Front label', 'Back label', 'Print exports'],
    relatedSlugs: ['packaging-design', 'brand-identity-design'],
    assets: designAssets('label', ['Front Label', 'Back Label', 'Bottle Mockup', 'Jar Mockup', 'Sheet Layout', 'Detail Crop']),
    theme: { primary: '#0E7490', accent: '#F43F5E' },
    seoTitle: 'Product Label Design Bangladesh',
    seoDescription: 'Product label design for food, cosmetics and retail brands.',
    seoKeywords: ['product label design', 'packaging design services'],
  },
  {
    slug: 'brochure-flyer-design',
    title: 'Brochure & Flyer Design',
    serviceGroup: 'packaging-print',
    serviceType: 'Print',
    serviceSubcategory: 'graphics-design',
    targetBusiness: 'Events, clinics, education, retail',
    pricingModel: 'one_time',
    shortDescription: 'Print and PDF promotional layouts.',
    outcomeLine: 'Clear flyers and brochures for offers and events.',
    fullDescription:
      'Business Problem: Text-heavy flyers get ignored. Solution: Structured brochure/flyer design with strong offer focus.',
    startingPrice: 3000,
    priceSuffix: '+',
    featured: false,
    popular: false,
    sortOrder: 60,
    deliverables: ['A4/A5 layouts', 'Print PDF', 'Social crop'],
    relatedSlugs: ['facebook-ads-creative', 'social-media-post-design'],
    assets: designAssets('print', ['Flyer Front', 'Flyer Back', 'Tri-fold', 'Poster', 'Offer Sheet', 'PDF Preview']),
    theme: { primary: '#1D4ED8', accent: '#DC2626' },
    seoTitle: 'Brochure and Flyer Design Bangladesh',
    seoDescription: 'Brochure, flyer and poster design for promotions and events.',
    seoKeywords: ['brochure design bangladesh', 'flyer design', 'graphic design services'],
  },
  {
    slug: 'visiting-card-design',
    title: 'Visiting Card Design',
    serviceGroup: 'branding-identity',
    serviceType: 'Branding',
    serviceSubcategory: 'graphics-design',
    targetBusiness: 'Professionals and SMEs',
    pricingModel: 'one_time',
    shortDescription: 'Clean business cards matched to your brand.',
    outcomeLine: 'Print-ready visiting card designs.',
    fullDescription:
      'Business Problem: Generic cards look unprofessional. Solution: Minimal, brand-aligned visiting card design.',
    startingPrice: 1500,
    priceSuffix: '',
    featured: false,
    popular: false,
    sortOrder: 65,
    deliverables: ['Front/back design', 'Print PDF'],
    relatedSlugs: ['logo-design', 'brand-identity-design'],
    assets: designAssets('card', ['Front', 'Back', 'Mockup', 'Dark Variant', 'Light Variant', 'QR Layout']),
    theme: { primary: '#334155', accent: '#2563EB' },
    seoTitle: 'Visiting Card Design Bangladesh',
    seoDescription: 'Business visiting card design with print-ready files.',
    seoKeywords: ['visiting card design bangladesh', 'business card design'],
  },
  {
    slug: 'meta-ads-management',
    title: 'Facebook & Instagram Ads Management',
    serviceGroup: 'facebook-instagram-ads',
    serviceType: 'Ads Management',
    serviceSubcategory: 'digital-marketing',
    targetBusiness: 'E-commerce and lead generation businesses',
    pricingModel: 'monthly',
    shortDescription: 'Managed Meta ads with creative testing and reporting.',
    outcomeLine: 'Structured campaigns with clear weekly reporting.',
    fullDescription:
      'Business Problem: Unmanaged ads waste budget without learning. Solution: Monthly Meta ads management covering setup, creative testing, audiences and optimization — with realistic reporting, not inflated ROAS claims.',
    startingPrice: 15000,
    priceSuffix: '+',
    featured: true,
    popular: true,
    sortOrder: 70,
    deliverables: [
      'Campaign setup',
      'Audience structure',
      'Creative testing',
      'Weekly optimization',
      'Monthly report',
    ],
    relatedSlugs: ['facebook-ads-creative', 'meta-pixel-capi-setup', 'ecommerce-marketing-package', 'lead-generation-campaigns'],
    assets: marketingScreens,
    theme: { primary: '#1877F2', accent: '#E1306C' },
    seoTitle: 'Facebook Ads Management Bangladesh | Meta Ads Management',
    seoDescription:
      'Facebook and Instagram ads management for Bangladesh businesses — setup, optimization and reporting.',
    seoKeywords: [
      'facebook ads management bangladesh',
      'meta ads management',
      'digital marketing agency bangladesh',
      'facebook ads management',
    ],
  },
  {
    slug: 'meta-pixel-capi-setup',
    title: 'Meta Pixel & Conversion API Setup',
    serviceGroup: 'facebook-instagram-ads',
    serviceType: 'Tracking',
    serviceSubcategory: 'digital-marketing',
    targetBusiness: 'Stores and lead funnels running Meta ads',
    pricingModel: 'one_time',
    shortDescription: 'Accurate event tracking for Meta campaigns.',
    outcomeLine: 'Pixel + CAPI events verified for key conversions.',
    fullDescription:
      'Business Problem: Broken tracking makes optimization guesswork. Solution: Pixel and Conversion API setup with event verification for purchases, leads and key actions.',
    startingPrice: 8000,
    priceSuffix: '+',
    featured: false,
    popular: false,
    sortOrder: 80,
    deliverables: ['Pixel install', 'CAPI setup', 'Event testing', 'Documentation'],
    relatedSlugs: ['meta-ads-management', 'ecommerce-marketing-package', 'facebook-ads-creative'],
    assets: marketingScreens.slice(0, 8),
    theme: { primary: '#0F766E', accent: '#2563EB' },
    seoTitle: 'Meta Pixel and Conversion API Setup Bangladesh',
    seoDescription: 'Meta Pixel and Conversion API setup for accurate ad tracking.',
    seoKeywords: ['meta pixel setup', 'conversion api setup', 'facebook ads management bangladesh'],
  },
  {
    slug: 'ecommerce-marketing-package',
    title: 'E-commerce Marketing Package',
    serviceGroup: 'ecommerce-marketing',
    serviceType: 'Growth',
    serviceSubcategory: 'digital-marketing',
    targetBusiness: 'Online stores and D2C brands',
    pricingModel: 'package',
    shortDescription: 'Ads, creatives and tracking for store growth.',
    outcomeLine: 'A coordinated ecommerce acquisition package.',
    fullDescription:
      'Business Problem: Stores run ads, creatives and tracking as separate silos. Solution: A package combining Meta ads structure, creatives and tracking guidance for ecommerce funnels.',
    startingPrice: 25000,
    priceSuffix: '+',
    featured: true,
    popular: true,
    sortOrder: 90,
    deliverables: ['Ads structure', 'Creative set', 'Pixel checklist', 'Retargeting plan', 'Reporting'],
    relatedSlugs: ['meta-ads-management', 'facebook-ads-creative', 'meta-pixel-capi-setup', 'social-media-post-design'],
    assets: [...marketingScreens.slice(0, 6), ...designAssets('ecom', ['Product Ad', 'Collection Ad', 'Offer Banner', 'Retargeting'])],
    theme: { primary: '#059669', accent: '#F59E0B' },
    seoTitle: 'E-commerce Marketing Services Bangladesh',
    seoDescription: 'E-commerce marketing packages with Meta ads, creatives and tracking.',
    seoKeywords: [
      'ecommerce marketing services',
      'ecommerce marketing agency',
      'digital marketing services',
    ],
  },
  {
    slug: 'lead-generation-campaigns',
    title: 'Lead Generation Campaigns',
    serviceGroup: 'lead-generation',
    serviceType: 'Lead Gen',
    serviceSubcategory: 'digital-marketing',
    targetBusiness: 'Services, education, real estate, B2B',
    pricingModel: 'monthly',
    shortDescription: 'Meta lead campaigns with form and follow-up structure.',
    outcomeLine: 'Qualified lead flow with clear funnel reporting.',
    fullDescription:
      'Business Problem: Lead forms fill with poor-quality contacts. Solution: Audience, offer and creative alignment with lead form setup and funnel reporting.',
    startingPrice: 12000,
    priceSuffix: '+',
    featured: true,
    popular: true,
    sortOrder: 100,
    deliverables: ['Lead campaign setup', 'Form configuration', 'Audience plan', 'Weekly report'],
    relatedSlugs: ['meta-ads-management', 'facebook-ads-creative', 'social-media-management'],
    assets: marketingScreens,
    theme: { primary: '#4F46E5', accent: '#14B8A6' },
    seoTitle: 'Lead Generation Services Bangladesh',
    seoDescription: 'Facebook lead generation campaigns for service and education businesses.',
    seoKeywords: ['lead generation services bangladesh', 'facebook lead ads', 'digital marketing services'],
  },
  {
    slug: 'social-media-management',
    title: 'Social Media Management',
    serviceGroup: 'social-media-management',
    serviceType: 'Management',
    serviceSubcategory: 'digital-marketing',
    targetBusiness: 'Local brands needing consistent presence',
    pricingModel: 'monthly',
    shortDescription: 'Monthly content planning, posting and light engagement.',
    outcomeLine: 'A planned content calendar with designed posts.',
    fullDescription:
      'Business Problem: Pages stay inactive or post randomly. Solution: Monthly social media management with content plan, designs and scheduled publishing.',
    startingPrice: 10000,
    priceSuffix: '+',
    featured: false,
    popular: false,
    sortOrder: 110,
    deliverables: ['Content calendar', 'Post designs', 'Scheduling', 'Basic insights'],
    relatedSlugs: ['social-media-post-design', 'facebook-ads-creative', 'brand-identity-design'],
    assets: designAssets('smm', [
      'Calendar Preview',
      'Feed Grid',
      'Post Sample 1',
      'Post Sample 2',
      'Story Set',
      'Insights Snapshot',
    ]),
    theme: { primary: '#DB2777', accent: '#6366F1' },
    seoTitle: 'Social Media Management Bangladesh',
    seoDescription: 'Monthly social media management with content planning and creatives.',
    seoKeywords: ['social media management bangladesh', 'digital marketing agency bangladesh'],
  },
  {
    slug: 'web-banner-ecommerce-creative',
    title: 'Web Banner & E-commerce Creative',
    serviceGroup: 'advertising-creative',
    serviceType: 'Design',
    serviceSubcategory: 'graphics-design',
    targetBusiness: 'Online stores and landing pages',
    pricingModel: 'package',
    shortDescription: 'Hero banners and product creatives for storefronts.',
    outcomeLine: 'Store-ready banners and product promo creatives.',
    fullDescription:
      'Business Problem: Store banners look outdated and mismatched. Solution: Web and ecommerce creative sets sized for hero, category and promo placements.',
    startingPrice: 4000,
    priceSuffix: '+',
    featured: false,
    popular: false,
    sortOrder: 120,
    deliverables: ['Hero banners', 'Category banners', 'Product creatives'],
    relatedSlugs: ['ecommerce-marketing-package', 'facebook-ads-creative', 'social-media-post-design'],
    assets: designAssets('web', ['Hero Banner', 'Category Banner', 'Promo Strip', 'Product Card', 'Sale Banner', 'Mobile Hero']),
    theme: { primary: '#0EA5E9', accent: '#F97316' },
    seoTitle: 'E-commerce Product Creative and Web Banner Design',
    seoDescription: 'Web banner and ecommerce product creative design for online stores.',
    seoKeywords: ['ecommerce product creative', 'web banner design', 'graphic design services'],
  },
  {
    slug: 'campaign-strategy-creative-testing',
    title: 'Campaign Strategy & Creative Testing',
    serviceGroup: 'facebook-instagram-ads',
    serviceType: 'Strategy',
    serviceSubcategory: 'digital-marketing',
    targetBusiness: 'Teams already spending on Meta ads',
    pricingModel: 'custom',
    shortDescription: 'Offer, audience and creative test plans for Meta.',
    outcomeLine: 'A clear test roadmap without vanity metric claims.',
    fullDescription:
      'Business Problem: Ads run without a test plan. Solution: Structured campaign strategy covering hooks, audiences and creative variants with measurement definitions you can trust.',
    startingPrice: 10000,
    priceSuffix: '+',
    featured: false,
    popular: false,
    sortOrder: 130,
    deliverables: ['Strategy doc', 'Test matrix', 'KPI definitions', 'Review call'],
    relatedSlugs: ['meta-ads-management', 'facebook-ads-creative', 'lead-generation-campaigns'],
    assets: marketingScreens.slice(0, 6),
    theme: { primary: '#4338CA', accent: '#F59E0B' },
    seoTitle: 'Meta Ads Campaign Strategy and Creative Testing',
    seoDescription: 'Campaign strategy and creative testing plans for Facebook and Instagram ads.',
    seoKeywords: ['campaign strategy', 'creative testing', 'meta ads management', 'digital marketing services'],
  },
];

export const CREATIVE_MARKETING_POPULAR_SLUGS = [
  'social-media-post-design',
  'meta-ads-management',
  'brand-identity-design',
  'ecommerce-marketing-package',
  'packaging-design',
  'lead-generation-campaigns',
  'facebook-ads-creative',
  'social-media-management',
] as const;
