-- Seed 40 marketplace products (BD pricing) across 5 product categories

INSERT INTO marketplace_products (
  slug,
  category_id,
  name,
  short_description,
  price,
  compare_price,
  stock,
  brand,
  is_featured,
  is_popular,
  currency,
  tags
)
SELECT
  s.slug,
  c.id,
  s.name,
  s.name || ' — premium listing for Bangladeshi businesses.',
  s.price,
  s.compare_price,
  s.stock,
  s.brand,
  s.is_featured,
  s.is_popular,
  'BDT',
  s.tags
FROM (
  VALUES
    ('dell-inspiron-business-laptop', 'electronics', 'Dell Inspiron Business Laptop', 72000::integer, 78000::integer, 12, 'Dell', true, false, ARRAY['laptop','business']::text[]),
    ('hp-probook-business-laptop', 'electronics', 'HP ProBook Business Laptop', 68000, 74000, 8, 'HP', false, false, ARRAY['laptop']::text[]),
    ('samsung-27-business-monitor', 'electronics', 'Samsung 27" Business Monitor', 28000, NULL::integer, 24, 'Samsung', false, true, ARRAY['monitor','display']::text[]),
    ('logitech-c920-hd-webcam', 'electronics', 'Logitech C920 HD Webcam', 6500, NULL, 45, 'Logitech', false, false, ARRAY['webcam']::text[]),
    ('mechanical-keyboard-pro', 'electronics', 'Mechanical Keyboard Pro', 4500, 5200, 30, 'Keychron', false, false, ARRAY['keyboard']::text[]),
    ('wireless-mouse-ergonomic', 'electronics', 'Wireless Mouse Ergonomic', 2200, NULL, 60, 'Logitech', false, false, ARRAY['mouse']::text[]),
    ('ups-1000va-backup', 'electronics', 'UPS 1000VA Backup', 8500, NULL, 18, 'Digital', false, false, ARRAY['ups','power']::text[]),
    ('external-ssd-1tb', 'electronics', 'External SSD 1TB', 9500, NULL, 35, 'Samsung', false, true, ARRAY['storage','ssd']::text[]),
    ('wireless-earbuds-pro', 'gadgets', 'Wireless Earbuds Pro', 3500, 4200, 80, 'SoundMax', true, true, ARRAY['earbuds','audio']::text[]),
    ('smart-watch-fitness', 'gadgets', 'Smart Watch Fitness', 5500, NULL, 40, 'FitBand', false, false, ARRAY['watch','wearable']::text[]),
    ('20000mah-power-bank', 'gadgets', '20000mAh Power Bank', 2800, NULL, 100, 'Anker', true, false, ARRAY['power-bank']::text[]),
    ('usb-c-hub-7-in-1', 'gadgets', 'USB-C Hub 7-in-1', 3200, NULL, 55, 'Baseus', false, false, ARRAY['hub','usb']::text[]),
    ('bluetooth-speaker-portable', 'gadgets', 'Bluetooth Speaker Portable', 4200, NULL, 42, 'JBL', false, false, ARRAY['speaker','audio']::text[]),
    ('phone-tripod-stand', 'gadgets', 'Phone Tripod Stand', 1200, NULL, 70, 'Ulanzi', false, false, ARRAY['tripod']::text[]),
    ('laptop-cooling-pad', 'gadgets', 'Laptop Cooling Pad', 1800, NULL, 38, 'CoolMaster', false, false, ARRAY['laptop-accessory']::text[]),
    ('ring-light-10', 'gadgets', 'Ring Light 10"', 2500, NULL, 50, 'Neewer', false, false, ARRAY['lighting','content']::text[]),
    ('thermal-pos-printer', 'office-solutions', 'Thermal POS Printer', 12500, NULL, 22, 'Xprinter', true, false, ARRAY['pos','printer']::text[]),
    ('barcode-scanner-usb', 'office-solutions', 'Barcode Scanner USB', 4500, NULL, 35, 'Honeywell', false, false, ARRAY['barcode','scanner']::text[]),
    ('cash-drawer-rj11', 'office-solutions', 'Cash Drawer RJ11', 6800, NULL, 15, 'Posiflex', false, false, ARRAY['cash-drawer','pos']::text[]),
    ('biometric-attendance-machine', 'office-solutions', 'Biometric Attendance Machine', 15000, NULL, 10, 'ZKTeco', false, true, ARRAY['attendance']::text[]),
    ('office-wifi-router-dual-band', 'office-solutions', 'Office WiFi Router Dual Band', 5500, NULL, 28, 'TP-Link', false, false, ARRAY['router','network']::text[]),
    ('document-scanner-a4', 'office-solutions', 'Document Scanner A4', 18500, NULL, 8, 'Canon', false, false, ARRAY['scanner']::text[]),
    ('label-printer-4x6', 'office-solutions', 'Label Printer 4x6', 9800, NULL, 14, 'Brother', false, false, ARRAY['label','shipping']::text[]),
    ('conference-speakerphone', 'office-solutions', 'Conference Speakerphone', 12000, NULL, 12, 'Jabra', false, false, ARRAY['conference','audio']::text[]),
    ('smart-cctv-4-channel-kit', 'smart-devices', 'Smart CCTV 4 Channel Kit', 22000, 25000, 16, 'Hikvision', true, false, ARRAY['cctv','security']::text[]),
    ('smart-door-lock-fingerprint', 'smart-devices', 'Smart Door Lock Fingerprint', 14500, NULL, 11, 'Tuya', false, false, ARRAY['lock','smart-home']::text[]),
    ('smart-led-bulb-pack-4', 'smart-devices', 'Smart LED Bulb Pack (4)', 2800, NULL, 48, 'Philips', false, false, ARRAY['lighting','smart']::text[]),
    ('smart-home-hub', 'smart-devices', 'Smart Home Hub', 8500, NULL, 20, 'Aqara', false, false, ARRAY['hub','automation']::text[]),
    ('smart-ip-camera-wifi', 'smart-devices', 'Smart IP Camera WiFi', 4200, NULL, 32, 'Ezviz', false, true, ARRAY['camera','wifi']::text[]),
    ('motion-sensor-pir', 'smart-devices', 'Motion Sensor PIR', 1500, NULL, 55, 'Tuya', false, false, ARRAY['sensor']::text[]),
    ('smart-plug-16a-2-pack', 'smart-devices', 'Smart Plug 16A (2 Pack)', 2200, NULL, 60, 'Sonoff', false, false, ARRAY['plug']::text[]),
    ('video-doorbell-wifi', 'smart-devices', 'Video Doorbell WiFi', 7500, NULL, 18, 'Xiaomi', false, false, ARRAY['doorbell','security']::text[]),
    ('pos-software-license-1-year', 'digital-products', 'POS Software License (1 Year)', 15000, NULL, 999, 'DeshiPOS', true, false, ARRAY['pos','license']::text[]),
    ('accounting-software-license', 'digital-products', 'Accounting Software License', 12000, NULL, 999, 'AccountsBD', false, false, ARRAY['accounting','license']::text[]),
    ('inventory-management-software', 'digital-products', 'Inventory Management Software', 18000, 22000, 999, 'StockFlow', false, true, ARRAY['inventory']::text[]),
    ('erp-starter-license', 'digital-products', 'ERP Starter License', 45000, NULL, 999, 'BizERP', false, false, ARRAY['erp','license']::text[]),
    ('crm-dashboard-template', 'digital-products', 'CRM Dashboard Template', 8000, NULL, 999, 'TemplateHub', false, false, ARRAY['crm','template']::text[]),
    ('hr-payroll-module-license', 'digital-products', 'HR Payroll Module License', 25000, NULL, 999, 'PayrollBD', false, false, ARRAY['hrm','payroll']::text[]),
    ('e-commerce-admin-dashboard-ui', 'digital-products', 'E-commerce Admin Dashboard UI', 6500, NULL, 999, 'UIForge', false, false, ARRAY['ui','template']::text[]),
    ('school-management-system-license', 'digital-products', 'School Management System License', 35000, NULL, 999, 'EduSoft', false, false, ARRAY['school','license']::text[])
) AS s(slug, cat_slug, name, price, compare_price, stock, brand, is_featured, is_popular, tags)
JOIN marketplace_product_categories c ON c.slug = s.cat_slug
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  stock = EXCLUDED.stock,
  brand = EXCLUDED.brand,
  is_featured = EXCLUDED.is_featured,
  is_popular = EXCLUDED.is_popular,
  tags = EXCLUDED.tags,
  category_id = EXCLUDED.category_id;
